/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.crm.dal.daointerface;

// auto generated imports
import com.born.fcs.crm.dal.dataobject.CutomerInfoVerifyMessageDO;
import org.springframework.dao.DataAccessException;

/**
 * A dao interface provides methods to access database table <tt>cutomer_info_verify_message</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cutomer_info_verify_message.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */

public interface CutomerInfoVerifyMessageDAO {
	/**
	 *  Insert one <tt>CutomerInfoVerifyMessageDO</tt> object to DB table <tt>cutomer_info_verify_message</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into cutomer_info_verify_message(error_key,customer_id,mobile_message,card_message,message_type,raw_add_time) values (?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param cutomerInfoVerifyMessage
	 *	@return String
	 *	@throws DataAccessException
	 */	 
    public String insert(CutomerInfoVerifyMessageDO cutomerInfoVerifyMessage) throws DataAccessException;

	/**
	 *  Query DB table <tt>cutomer_info_verify_message</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select error_key, customer_id, mobile_message, card_message, message_type, raw_add_time, raw_update_time from cutomer_info_verify_message where (error_key = ?)</tt>
	 *
	 *	@param errorKey
	 *	@return CutomerInfoVerifyMessageDO
	 *	@throws DataAccessException
	 */	 
    public CutomerInfoVerifyMessageDO findByErrorKey(String errorKey) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>cutomer_info_verify_message</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from cutomer_info_verify_message where (error_key = ?)</tt>
	 *
	 *	@param errorKey
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByErrorKey(String errorKey) throws DataAccessException;

	/**
	 *  Update DB table <tt>cutomer_info_verify_message</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update cutomer_info_verify_message set customer_id=?, mobile_message=?, card_message=?, message_type=? where (error_key = ?)</tt>
	 *
	 *	@param cutomerInfoVerifyMessage
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateByErrorKey(CutomerInfoVerifyMessageDO cutomerInfoVerifyMessage) throws DataAccessException;

}