/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.fm.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.fcs.fm.dal.daointerface.BudgetDAO;


// auto generated imports
import com.born.fcs.fm.dal.dataobject.BudgetDO;
import org.springframework.dao.DataAccessException;
import com.born.fcs.fm.dal.queryCondition.BudgetQueryCondition;
import java.util.List;

/**
 * An ibatis based implementation of dao interface <tt>com.born.fcs.fm.dal.daointerface.BudgetDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/budget.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 
@SuppressWarnings("unchecked")

public class IbatisBudgetDAO extends SqlMapClientDaoSupport implements BudgetDAO {
	/**
	 *  Insert one <tt>BudgetDO</tt> object to DB table <tt>budget</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into budget(budget_id,start_time,end_time,period,period_value,budget_dept_id,budget_dept_name,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param budget
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(BudgetDO budget) throws DataAccessException {
    	if (budget == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-BUDGET-INSERT", budget);

        return budget.getBudgetId();
    }

	/**
	 *  Update DB table <tt>budget</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update budget set start_time=?, end_time=?, period=?, period_value=?, budget_dept_id=?, budget_dept_name=? where (budget_id = ?)</tt>
	 *
	 *	@param budget
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(BudgetDO budget) throws DataAccessException {
    	if (budget == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-BUDGET-UPDATE", budget);
    }

	/**
	 *  Query DB table <tt>budget</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select budget_id, start_time, end_time, period, period_value, budget_dept_id, budget_dept_name, raw_add_time, raw_update_time from budget where (budget_id = ?)</tt>
	 *
	 *	@param budgetId
	 *	@return BudgetDO
	 *	@throws DataAccessException
	 */	 
    public BudgetDO findById(long budgetId) throws DataAccessException {
        Long param = new Long(budgetId);

        return (BudgetDO) getSqlMapClientTemplate().queryForObject("MS-BUDGET-FIND-BY-ID", param);

    }

	/**
	 *  Delete records from DB table <tt>budget</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from budget where (budget_id = ?)</tt>
	 *
	 *	@param budgetId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long budgetId) throws DataAccessException {
        Long param = new Long(budgetId);

        return getSqlMapClientTemplate().delete("MS-BUDGET-DELETE-BY-ID", param);
    }

	/**
	 *  Query DB table <tt>budget</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from budget where (1 = 1)</tt>
	 *
	 *	@param condition
	 *	@return List<BudgetDO>
	 *	@throws DataAccessException
	 */	 
    public List<BudgetDO> findByCondition(BudgetQueryCondition condition) throws DataAccessException {

        return getSqlMapClientTemplate().queryForList("MS-BUDGET-FIND-BY-CONDITION", condition);

    }

	/**
	 *  Query DB table <tt>budget</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from budget where (1 = 1)</tt>
	 *
	 *	@param condition
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(BudgetQueryCondition condition) throws DataAccessException {

	    Long retObj = (Long) getSqlMapClientTemplate().queryForObject("MS-BUDGET-FIND-BY-CONDITION-COUNT", condition);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.longValue();
		}

    }

}