/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.fm.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.fcs.fm.dal.daointerface.FormTravelExpenseDetailDAO;


// auto generated imports
import com.born.fcs.fm.dal.dataobject.FormTravelExpenseDetailDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Map;
	import java.util.HashMap;
	
/**
 * An ibatis based implementation of dao interface <tt>com.born.fcs.fm.dal.daointerface.FormTravelExpenseDetailDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/form_travel_expense_detail.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 
@SuppressWarnings({ "unchecked", "rawtypes" })

public class IbatisFormTravelExpenseDetailDAO extends SqlMapClientDaoSupport implements FormTravelExpenseDetailDAO {
	/**
	 *  Insert one <tt>FormTravelExpenseDetailDO</tt> object to DB table <tt>form_travel_expense_detail</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into form_travel_expense_detail(detail_id,travel_id,start_time,end_time,days,start_place,end_place,traffic_amount,hotel_amount,tax_amount,meals_amount,allowance_amount,other_amount,total_amount,dept_id,dept_name,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param formTravelExpenseDetail
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(FormTravelExpenseDetailDO formTravelExpenseDetail) throws DataAccessException {
    	if (formTravelExpenseDetail == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-FORM-TRAVEL-EXPENSE-DETAIL-INSERT", formTravelExpenseDetail);

        return formTravelExpenseDetail.getDetailId();
    }

	/**
	 *  Update DB table <tt>form_travel_expense_detail</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update form_travel_expense_detail set travel_id=?, start_time=?, end_time=?, days=?, start_place=?, end_place=?, traffic_amount=?, hotel_amount=?, tax_amount=?, meals_amount=?, allowance_amount=?, other_amount=?, total_amount=?, dept_id=?, dept_name=? where (detail_id = ?)</tt>
	 *
	 *	@param formTravelExpenseDetail
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(FormTravelExpenseDetailDO formTravelExpenseDetail) throws DataAccessException {
    	if (formTravelExpenseDetail == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-FORM-TRAVEL-EXPENSE-DETAIL-UPDATE", formTravelExpenseDetail);
    }

	/**
	 *  Query DB table <tt>form_travel_expense_detail</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select detail_id, travel_id, start_time, end_time, days, start_place, end_place, traffic_amount, hotel_amount, tax_amount, meals_amount, allowance_amount, other_amount, total_amount, dept_id, dept_name, raw_add_time, raw_update_time from form_travel_expense_detail where (detail_id = ?)</tt>
	 *
	 *	@param detailId
	 *	@return FormTravelExpenseDetailDO
	 *	@throws DataAccessException
	 */	 
    public FormTravelExpenseDetailDO findById(long detailId) throws DataAccessException {
        Long param = new Long(detailId);

        return (FormTravelExpenseDetailDO) getSqlMapClientTemplate().queryForObject("MS-FORM-TRAVEL-EXPENSE-DETAIL-FIND-BY-ID", param);

    }

	/**
	 *  Delete records from DB table <tt>form_travel_expense_detail</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from form_travel_expense_detail where (detail_id = ?)</tt>
	 *
	 *	@param detailId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long detailId) throws DataAccessException {
        Long param = new Long(detailId);

        return getSqlMapClientTemplate().delete("MS-FORM-TRAVEL-EXPENSE-DETAIL-DELETE-BY-ID", param);
    }

	/**
	 *  Query DB table <tt>form_travel_expense_detail</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select detail_id, travel_id, start_time, end_time, days, start_place, end_place, traffic_amount, hotel_amount, tax_amount, meals_amount, allowance_amount, other_amount, total_amount, dept_id, dept_name, raw_add_time, raw_update_time from form_travel_expense_detail where (travel_id = ?)</tt>
	 *
	 *	@param travelId
	 *	@return List<FormTravelExpenseDetailDO>
	 *	@throws DataAccessException
	 */	 
    public List<FormTravelExpenseDetailDO> findByTravelId(long travelId) throws DataAccessException {
        Long param = new Long(travelId);

        return getSqlMapClientTemplate().queryForList("MS-FORM-TRAVEL-EXPENSE-DETAIL-FIND-BY-TRAVEL-ID", param);

    }

	/**
	 *  Query DB table <tt>form_travel_expense_detail</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select d.* from form_travel_expense e, form_travel_expense_detail d, form f where ((d.travel_id = e.travel_id) AND (e.form_id = f.form_id) AND (f.status IN ('APPROVAL', 'SUBMIT', 'AUDITING')))</tt>
	 *
	 *	@param deptId
	 *	@param applyTimeStart
	 *	@param applyTimeEnd
	 *	@return List<FormTravelExpenseDetailDO>
	 *	@throws DataAccessException
	 */	 
    public List<FormTravelExpenseDetailDO> findApprlInfoByDeptId(String deptId, String applyTimeStart, String applyTimeEnd) throws DataAccessException {
        Map param = new HashMap();

        param.put("deptId", deptId);
        param.put("applyTimeStart", applyTimeStart);
        param.put("applyTimeEnd", applyTimeEnd);

        return getSqlMapClientTemplate().queryForList("MS-FORM-TRAVEL-EXPENSE-DETAIL-FIND-APPRL-INFO-BY-DEPT-ID", param);

    }

}