/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.dataobject;

import java.io.Serializable;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

// auto generated imports
import com.yjf.common.lang.util.money.Money;
import java.util.Date;

/**
 * A data object class directly models database table <tt>f_afterwards_check_base</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/f_afterwards_check_base.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
public class FAfterwardsCheckBaseDO implements Serializable{
	/** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========

	private long baseId;

	private long formId;

	private String projectName;

	private String projectCode;

	private long customerId;

	private String customerName;

	private String busiType;

	private String busiTypeName;

	private Money amount = new Money(0, 0);

	private Date startTime;

	private Date endTime;

	private String busiManagerName;

	private String riskManagerName;

	private String capitalChannelName;

	private String loanPurpose;

	private String spendWay;

	private int timeLimit;

	private String timeUnit;

	private Money loanedAmount = new Money(0, 0);

	private Money repayedAmount = new Money(0, 0);

	private Money availableAmount = new Money(0, 0);

	private Money releaseBalance = new Money(0, 0);

	private Money guaranteeAmount = new Money(0, 0);

	private Money guaranteeDeposit = new Money(0, 0);

	private int collectYear;

	private int collectMonth;

	private String collectData;

	private String feedbackOpinion;

	private String customerOpinion;

	private String remark1;

	private String remark2;

	private Date rawAddTime;

	private Date rawUpdateTime;

    //========== getters and setters ==========

	public long getBaseId() {
		return baseId;
	}
	
	public void setBaseId(long baseId) {
		this.baseId = baseId;
	}

	public long getFormId() {
		return formId;
	}
	
	public void setFormId(long formId) {
		this.formId = formId;
	}

	public String getProjectName() {
		return projectName;
	}
	
	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getProjectCode() {
		return projectCode;
	}
	
	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode;
	}

	public long getCustomerId() {
		return customerId;
	}
	
	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	public String getCustomerName() {
		return customerName;
	}
	
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getBusiType() {
		return busiType;
	}
	
	public void setBusiType(String busiType) {
		this.busiType = busiType;
	}

	public String getBusiTypeName() {
		return busiTypeName;
	}
	
	public void setBusiTypeName(String busiTypeName) {
		this.busiTypeName = busiTypeName;
	}

	public Money getAmount() {
		return amount;
	}
	
	public void setAmount(Money amount) {
		if (amount == null) {
			this.amount = new Money(0, 0);
		} else {
			this.amount = amount;
		}
	}

	public Date getStartTime() {
		return startTime;
	}
	
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return endTime;
	}
	
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getBusiManagerName() {
		return busiManagerName;
	}
	
	public void setBusiManagerName(String busiManagerName) {
		this.busiManagerName = busiManagerName;
	}

	public String getRiskManagerName() {
		return riskManagerName;
	}
	
	public void setRiskManagerName(String riskManagerName) {
		this.riskManagerName = riskManagerName;
	}

	public String getCapitalChannelName() {
		return capitalChannelName;
	}
	
	public void setCapitalChannelName(String capitalChannelName) {
		this.capitalChannelName = capitalChannelName;
	}

	public String getLoanPurpose() {
		return loanPurpose;
	}
	
	public void setLoanPurpose(String loanPurpose) {
		this.loanPurpose = loanPurpose;
	}

	public String getSpendWay() {
		return spendWay;
	}
	
	public void setSpendWay(String spendWay) {
		this.spendWay = spendWay;
	}

	public int getTimeLimit() {
		return timeLimit;
	}
	
	public void setTimeLimit(int timeLimit) {
		this.timeLimit = timeLimit;
	}

	public String getTimeUnit() {
		return timeUnit;
	}
	
	public void setTimeUnit(String timeUnit) {
		this.timeUnit = timeUnit;
	}

	public Money getLoanedAmount() {
		return loanedAmount;
	}
	
	public void setLoanedAmount(Money loanedAmount) {
		if (loanedAmount == null) {
			this.loanedAmount = new Money(0, 0);
		} else {
			this.loanedAmount = loanedAmount;
		}
	}

	public Money getRepayedAmount() {
		return repayedAmount;
	}
	
	public void setRepayedAmount(Money repayedAmount) {
		if (repayedAmount == null) {
			this.repayedAmount = new Money(0, 0);
		} else {
			this.repayedAmount = repayedAmount;
		}
	}

	public Money getAvailableAmount() {
		return availableAmount;
	}
	
	public void setAvailableAmount(Money availableAmount) {
		if (availableAmount == null) {
			this.availableAmount = new Money(0, 0);
		} else {
			this.availableAmount = availableAmount;
		}
	}

	public Money getReleaseBalance() {
		return releaseBalance;
	}
	
	public void setReleaseBalance(Money releaseBalance) {
		if (releaseBalance == null) {
			this.releaseBalance = new Money(0, 0);
		} else {
			this.releaseBalance = releaseBalance;
		}
	}

	public Money getGuaranteeAmount() {
		return guaranteeAmount;
	}
	
	public void setGuaranteeAmount(Money guaranteeAmount) {
		if (guaranteeAmount == null) {
			this.guaranteeAmount = new Money(0, 0);
		} else {
			this.guaranteeAmount = guaranteeAmount;
		}
	}

	public Money getGuaranteeDeposit() {
		return guaranteeDeposit;
	}
	
	public void setGuaranteeDeposit(Money guaranteeDeposit) {
		if (guaranteeDeposit == null) {
			this.guaranteeDeposit = new Money(0, 0);
		} else {
			this.guaranteeDeposit = guaranteeDeposit;
		}
	}

	public int getCollectYear() {
		return collectYear;
	}
	
	public void setCollectYear(int collectYear) {
		this.collectYear = collectYear;
	}

	public int getCollectMonth() {
		return collectMonth;
	}
	
	public void setCollectMonth(int collectMonth) {
		this.collectMonth = collectMonth;
	}

	public String getCollectData() {
		return collectData;
	}
	
	public void setCollectData(String collectData) {
		this.collectData = collectData;
	}

	public String getFeedbackOpinion() {
		return feedbackOpinion;
	}
	
	public void setFeedbackOpinion(String feedbackOpinion) {
		this.feedbackOpinion = feedbackOpinion;
	}

	public String getCustomerOpinion() {
		return customerOpinion;
	}
	
	public void setCustomerOpinion(String customerOpinion) {
		this.customerOpinion = customerOpinion;
	}

	public String getRemark1() {
		return remark1;
	}
	
	public void setRemark1(String remark1) {
		this.remark1 = remark1;
	}

	public String getRemark2() {
		return remark2;
	}
	
	public void setRemark2(String remark2) {
		this.remark2 = remark2;
	}

	public Date getRawAddTime() {
		return rawAddTime;
	}
	
	public void setRawAddTime(Date rawAddTime) {
		this.rawAddTime = rawAddTime;
	}

	public Date getRawUpdateTime() {
		return rawUpdateTime;
	}
	
	public void setRawUpdateTime(Date rawUpdateTime) {
		this.rawUpdateTime = rawUpdateTime;
	}


	/**
     * @return
     *
     * @see java.lang.Object#toString()
     */
	@Override
    public String toString() {

        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
