/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.dataobject;

import java.util.Date;
import java.util.List;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.born.fcs.pm.dataobject.FormProjectDO;
// auto generated imports
import com.yjf.common.lang.util.money.Money;

/**
 * A data object class directly models database table
 * <tt>f_credit_condition_confirm</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access
 * Layer) code generation utility specially developed for <tt>paygw</tt>
 * project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may be
 * OVERWRITTEN by someone else. To modify the file, you should go to directory
 * <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and find the corresponding
 * configuration file (<tt>tables/f_credit_condition_confirm.xml</tt>). Modify
 * the configuration file according to your needs, then run
 * <tt>specialmer-dalgen</tt> to generate this file.
 *
 * @author peigen
 */
public class FCreditConditionConfirmDO extends FormProjectDO {
	/** Comment for <code>serialVersionUID</code> */
	private static final long serialVersionUID = -4282603875229233564L;
	
	//========== properties ==========
	
	private long confirmId;
	
	private long formId;
	
	private String projectCode;
	
	private String projectName;
	
	private String contractNo;
	
	private long customerId;
	
	private String customerName;
	
	private String customerType;
	
	private String busiType;
	
	private String busiTypeName;
	
	private int timeLimit;
	
	private String timeUnit;
	
	private Money amount = new Money(0, 0);
	
	private long institutionId;
	
	private String institutionName;
	private String isMargin;
	private String remark;
	
	private Date rawAddTime;
	
	private Date rawUpdateTime;
	
	private long busiManagerbId;
	private String busiManagerbAccount;
	private String busiManagerbName;
	
	//查询条件
	List<Long> deptIdList;
	
	List<String> statusList;
	
	long loginUserId;
	
	long pageSize;
	
	long limitStart;
	
	String sortCol;
	
	String sortOrder;
	
	//========== getters and setters ==========
	
	@Override
	public long getBusiManagerbId() {
		return busiManagerbId;
	}
	
	@Override
	public void setBusiManagerbId(long busiManagerbId) {
		this.busiManagerbId = busiManagerbId;
	}
	
	public String getBusiManagerbAccount() {
		return busiManagerbAccount;
	}
	
	public void setBusiManagerbAccount(String busiManagerbAccount) {
		this.busiManagerbAccount = busiManagerbAccount;
	}
	
	@Override
	public String getBusiManagerbName() {
		return busiManagerbName;
	}
	
	@Override
	public void setBusiManagerbName(String busiManagerbName) {
		this.busiManagerbName = busiManagerbName;
	}
	
	public long getConfirmId() {
		return confirmId;
	}
	
	public void setConfirmId(long confirmId) {
		this.confirmId = confirmId;
	}
	
	@Override
	public long getFormId() {
		return formId;
	}
	
	@Override
	public void setFormId(long formId) {
		this.formId = formId;
	}
	
	@Override
	public String getProjectCode() {
		return projectCode;
	}
	
	@Override
	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode;
	}
	
	@Override
	public String getProjectName() {
		return projectName;
	}
	
	@Override
	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}
	
	public String getContractNo() {
		return contractNo;
	}
	
	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}
	
	@Override
	public long getCustomerId() {
		return customerId;
	}
	
	@Override
	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}
	
	@Override
	public String getCustomerName() {
		return customerName;
	}
	
	@Override
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}
	
	@Override
	public String getCustomerType() {
		return customerType;
	}
	
	@Override
	public void setCustomerType(String customerType) {
		this.customerType = customerType;
	}
	
	@Override
	public String getBusiType() {
		return busiType;
	}
	
	@Override
	public void setBusiType(String busiType) {
		this.busiType = busiType;
	}
	
	@Override
	public String getBusiTypeName() {
		return busiTypeName;
	}
	
	@Override
	public void setBusiTypeName(String busiTypeName) {
		this.busiTypeName = busiTypeName;
	}
	
	@Override
	public int getTimeLimit() {
		return timeLimit;
	}
	
	@Override
	public void setTimeLimit(int timeLimit) {
		this.timeLimit = timeLimit;
	}
	
	@Override
	public String getTimeUnit() {
		return timeUnit;
	}
	
	@Override
	public void setTimeUnit(String timeUnit) {
		this.timeUnit = timeUnit;
	}
	
	@Override
	public Money getAmount() {
		return amount;
	}
	
	@Override
	public void setAmount(Money amount) {
		if (amount == null) {
			this.amount = new Money(0, 0);
		} else {
			this.amount = amount;
		}
	}
	
	public long getInstitutionId() {
		return institutionId;
	}
	
	public void setInstitutionId(long institutionId) {
		this.institutionId = institutionId;
	}
	
	public String getInstitutionName() {
		return institutionName;
	}
	
	public void setInstitutionName(String institutionName) {
		this.institutionName = institutionName;
	}
	
	public String getRemark() {
		return remark;
	}
	
	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	public Date getRawAddTime() {
		return rawAddTime;
	}
	
	public void setRawAddTime(Date rawAddTime) {
		this.rawAddTime = rawAddTime;
	}
	
	public Date getRawUpdateTime() {
		return rawUpdateTime;
	}
	
	public void setRawUpdateTime(Date rawUpdateTime) {
		this.rawUpdateTime = rawUpdateTime;
	}
	
	public List<Long> getDeptIdList() {
		return deptIdList;
	}
	
	public void setDeptIdList(List<Long> deptIdList) {
		this.deptIdList = deptIdList;
	}
	
	public List<String> getStatusList() {
		return statusList;
	}
	
	public void setStatusList(List<String> statusList) {
		this.statusList = statusList;
	}
	
	public long getLoginUserId() {
		return loginUserId;
	}
	
	public void setLoginUserId(long loginUserId) {
		this.loginUserId = loginUserId;
	}
	
	public long getPageSize() {
		return pageSize;
	}
	
	public void setPageSize(long pageSize) {
		this.pageSize = pageSize;
	}
	
	public long getLimitStart() {
		return limitStart;
	}
	
	public void setLimitStart(long limitStart) {
		this.limitStart = limitStart;
	}
	
	public String getSortCol() {
		return sortCol;
	}
	
	public void setSortCol(String sortCol) {
		this.sortCol = sortCol;
	}
	
	public String getSortOrder() {
		return sortOrder;
	}
	
	public void setSortOrder(String sortOrder) {
		this.sortOrder = sortOrder;
	}
	
	public String getIsMargin() {
		return isMargin;
	}
	
	public void setIsMargin(String isMargin) {
		this.isMargin = isMargin;
	}
	
	/**
	 * @return
	 *
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		
		return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
	}
}
