/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.dataobject;

import java.io.Serializable;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

// auto generated imports
import java.util.Date;
import com.yjf.common.lang.util.money.Money;

/**
 * A data object class directly models database table <tt>view_project_charge_detail</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/view_project_charge_detail.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
public class ViewProjectChargeDetailDO implements Serializable{
	/** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========

	private String projectCode;

	private String projectName;

	private long customerId;

	private String customerName;

	private String customerType;

	private String busiType;

	private String busiTypeName;

	private long busiManagerId;

	private String busiManagerAccount;

	private String busiManagerName;

	private Date startTime;

	private Date endTime;

	private Money balance = new Money(0, 0);

	private Money compPrincipalAmount = new Money(0, 0);

	private String feeType;

	private Money chargeAmount = new Money(0, 0);

	private Date chargeTime;

	private Date chargeConfirmTime;

	private String chargeAccount;

	private Money chargeBase = new Money(0, 0);

	private double chargeRate;

	private Date chargeStartTime;

	private Date chargeEndTime;

    //========== getters and setters ==========

	public String getProjectCode() {
		return projectCode;
	}
	
	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode;
	}

	public String getProjectName() {
		return projectName;
	}
	
	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public long getCustomerId() {
		return customerId;
	}
	
	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	public String getCustomerName() {
		return customerName;
	}
	
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getCustomerType() {
		return customerType;
	}
	
	public void setCustomerType(String customerType) {
		this.customerType = customerType;
	}

	public String getBusiType() {
		return busiType;
	}
	
	public void setBusiType(String busiType) {
		this.busiType = busiType;
	}

	public String getBusiTypeName() {
		return busiTypeName;
	}
	
	public void setBusiTypeName(String busiTypeName) {
		this.busiTypeName = busiTypeName;
	}

	public long getBusiManagerId() {
		return busiManagerId;
	}
	
	public void setBusiManagerId(long busiManagerId) {
		this.busiManagerId = busiManagerId;
	}

	public String getBusiManagerAccount() {
		return busiManagerAccount;
	}
	
	public void setBusiManagerAccount(String busiManagerAccount) {
		this.busiManagerAccount = busiManagerAccount;
	}

	public String getBusiManagerName() {
		return busiManagerName;
	}
	
	public void setBusiManagerName(String busiManagerName) {
		this.busiManagerName = busiManagerName;
	}

	public Date getStartTime() {
		return startTime;
	}
	
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return endTime;
	}
	
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Money getBalance() {
		return balance;
	}
	
	public void setBalance(Money balance) {
		if (balance == null) {
			this.balance = new Money(0, 0);
		} else {
			this.balance = balance;
		}
	}

	public Money getCompPrincipalAmount() {
		return compPrincipalAmount;
	}
	
	public void setCompPrincipalAmount(Money compPrincipalAmount) {
		if (compPrincipalAmount == null) {
			this.compPrincipalAmount = new Money(0, 0);
		} else {
			this.compPrincipalAmount = compPrincipalAmount;
		}
	}

	public String getFeeType() {
		return feeType;
	}
	
	public void setFeeType(String feeType) {
		this.feeType = feeType;
	}

	public Money getChargeAmount() {
		return chargeAmount;
	}
	
	public void setChargeAmount(Money chargeAmount) {
		if (chargeAmount == null) {
			this.chargeAmount = new Money(0, 0);
		} else {
			this.chargeAmount = chargeAmount;
		}
	}

	public Date getChargeTime() {
		return chargeTime;
	}
	
	public void setChargeTime(Date chargeTime) {
		this.chargeTime = chargeTime;
	}

	public Date getChargeConfirmTime() {
		return chargeConfirmTime;
	}
	
	public void setChargeConfirmTime(Date chargeConfirmTime) {
		this.chargeConfirmTime = chargeConfirmTime;
	}

	public String getChargeAccount() {
		return chargeAccount;
	}
	
	public void setChargeAccount(String chargeAccount) {
		this.chargeAccount = chargeAccount;
	}

	public Money getChargeBase() {
		return chargeBase;
	}
	
	public void setChargeBase(Money chargeBase) {
		if (chargeBase == null) {
			this.chargeBase = new Money(0, 0);
		} else {
			this.chargeBase = chargeBase;
		}
	}

	public double getChargeRate() {
		return chargeRate;
	}
	
	public void setChargeRate(double chargeRate) {
		this.chargeRate = chargeRate;
	}

	public Date getChargeStartTime() {
		return chargeStartTime;
	}
	
	public void setChargeStartTime(Date chargeStartTime) {
		this.chargeStartTime = chargeStartTime;
	}

	public Date getChargeEndTime() {
		return chargeEndTime;
	}
	
	public void setChargeEndTime(Date chargeEndTime) {
		this.chargeEndTime = chargeEndTime;
	}


	/**
     * @return
     *
     * @see java.lang.Object#toString()
     */
	@Override
    public String toString() {

        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
