/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.daointerface;

// auto generated imports
import com.born.fcs.pm.dal.dataobject.FCouncilSummaryProjectGuarantorDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>f_council_summary_project_guarantor</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/f_council_summary_project_guarantor.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
 @SuppressWarnings("rawtypes") 
public interface FCouncilSummaryProjectGuarantorDAO {
	/**
	 *  Insert one <tt>FCouncilSummaryProjectGuarantorDO</tt> object to DB table <tt>f_council_summary_project_guarantor</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into f_council_summary_project_guarantor(id,sp_id,guarantor_type,guarantor,guarantee_amount,guarantee_way,sort_order,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param FCouncilSummaryProjectGuarantor
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(FCouncilSummaryProjectGuarantorDO FCouncilSummaryProjectGuarantor) throws DataAccessException;

	/**
	 *  Update DB table <tt>f_council_summary_project_guarantor</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update f_council_summary_project_guarantor set sp_id=?, guarantor_type=?, guarantor=?, guarantee_amount=?, guarantee_way=?, sort_order=? where (id = ?)</tt>
	 *
	 *	@param FCouncilSummaryProjectGuarantor
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(FCouncilSummaryProjectGuarantorDO FCouncilSummaryProjectGuarantor) throws DataAccessException;

	/**
	 *  Query DB table <tt>f_council_summary_project_guarantor</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_council_summary_project_guarantor where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return FCouncilSummaryProjectGuarantorDO
	 *	@throws DataAccessException
	 */	 
    public FCouncilSummaryProjectGuarantorDO findById(long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>f_council_summary_project_guarantor</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_council_summary_project_guarantor where (sp_id = ?)</tt>
	 *
	 *	@param spId
	 *	@return List<FCouncilSummaryProjectGuarantorDO>
	 *	@throws DataAccessException
	 */	 
    public List<FCouncilSummaryProjectGuarantorDO> findBySpId(long spId) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>f_council_summary_project_guarantor</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_council_summary_project_guarantor where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>f_council_summary_project_guarantor</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_council_summary_project_guarantor where (sp_id = ?)</tt>
	 *
	 *	@param spId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteBySpId(long spId) throws DataAccessException;

}