/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.daointerface;

// auto generated imports
import com.born.fcs.pm.dal.dataobject.FRiskReviewReportDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>f_risk_review_report</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/f_risk_review_report.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
 @SuppressWarnings("rawtypes") 
public interface FRiskReviewReportDAO {
	/**
	 *  Insert one <tt>FRiskReviewReportDO</tt> object to DB table <tt>f_risk_review_report</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into f_risk_review_report(id,form_id,project_code,project_name,customer_id,customer_name,report_content,case_info,preserve_content,audit_opinion,synthesize_opinion,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param FRiskReviewReport
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(FRiskReviewReportDO FRiskReviewReport) throws DataAccessException;

	/**
	 *  Update DB table <tt>f_risk_review_report</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update f_risk_review_report set form_id=?, project_code=?, project_name=?, customer_id=?, customer_name=?, report_content=?, case_info=?, preserve_content=?, audit_opinion=?, synthesize_opinion=? where (id = ?)</tt>
	 *
	 *	@param FRiskReviewReport
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(FRiskReviewReportDO FRiskReviewReport) throws DataAccessException;

	/**
	 *  Query DB table <tt>f_risk_review_report</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, form_id, project_code, project_name, customer_id, customer_name, report_content, case_info, preserve_content, audit_opinion, synthesize_opinion, raw_add_time, raw_update_time from f_risk_review_report where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return FRiskReviewReportDO
	 *	@throws DataAccessException
	 */	 
    public FRiskReviewReportDO findById(long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>f_risk_review_report</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, form_id, project_code, project_name, customer_id, customer_name, report_content, case_info, preserve_content, audit_opinion, synthesize_opinion, raw_add_time, raw_update_time from f_risk_review_report where (form_id = ?)</tt>
	 *
	 *	@param formId
	 *	@return FRiskReviewReportDO
	 *	@throws DataAccessException
	 */	 
    public FRiskReviewReportDO findByFormId(long formId) throws DataAccessException;

	/**
	 *  Query DB table <tt>f_risk_review_report</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, form_id, project_code, project_name, customer_id, customer_name, report_content, case_info, preserve_content, audit_opinion, synthesize_opinion, raw_add_time, raw_update_time from f_risk_review_report where (project_code = ?)</tt>
	 *
	 *	@param projectCode
	 *	@return FRiskReviewReportDO
	 *	@throws DataAccessException
	 */	 
    public FRiskReviewReportDO findByProjectCode(String projectCode) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>f_risk_review_report</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_risk_review_report where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>f_risk_review_report</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_risk_review_report where (form_id = ?)</tt>
	 *
	 *	@param formId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByFormId(long formId) throws DataAccessException;

	/**
	 *  Query DB table <tt>f_risk_review_report</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from f_risk_review_report</tt>
	 *
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findAllCount() throws DataAccessException;

	/**
	 *  Query DB table <tt>f_risk_review_report</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, form_id, project_code, project_name, customer_id, customer_name, report_content, case_info, preserve_content, audit_opinion, synthesize_opinion, raw_add_time, raw_update_time from f_risk_review_report where (id = ?)</tt>
	 *
	 *	@param FRiskReviewReport
	 *	@param limitStart
	 *	@param pageSize
	 *	@return List<FRiskReviewReportDO>
	 *	@throws DataAccessException
	 */	 
    public List<FRiskReviewReportDO> findByCondition(FRiskReviewReportDO FRiskReviewReport, long limitStart, long pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>f_risk_review_report</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, form_id, project_code, project_name, customer_id, customer_name, report_content, case_info, preserve_content, audit_opinion, synthesize_opinion, raw_add_time, raw_update_time from f_risk_review_report where (id = ?)</tt>
	 *
	 *	@param FRiskReviewReport
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(FRiskReviewReportDO FRiskReviewReport) throws DataAccessException;

}