/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.fcs.pm.dal.daointerface.BusiTypeDAO;


// auto generated imports
import com.born.fcs.pm.dal.dataobject.BusiTypeDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Map;
	import java.util.HashMap;
	
/**
 * An ibatis based implementation of dao interface <tt>com.born.fcs.pm.dal.daointerface.BusiTypeDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/busi_type.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 
@SuppressWarnings({ "unchecked", "rawtypes" })

public class IbatisBusiTypeDAO extends SqlMapClientDaoSupport implements BusiTypeDAO {
	/**
	 *  Insert one <tt>BusiTypeDO</tt> object to DB table <tt>busi_type</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into busi_type(code,name,parent_id,customer_type,has_children,setup_form_code,sort_order,is_del,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param busiType
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(BusiTypeDO busiType) throws DataAccessException {
    	if (busiType == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-BUSI-TYPE-INSERT", busiType);

        return busiType.getId();
    }

	/**
	 *  Update DB table <tt>busi_type</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update busi_type set code=?, name=?, parent_id=?, customer_type=?, has_children=?, setup_form_code=?, sort_order=?, is_del=? where (id = ?)</tt>
	 *
	 *	@param busiType
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(BusiTypeDO busiType) throws DataAccessException {
    	if (busiType == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-BUSI-TYPE-UPDATE", busiType);
    }

	/**
	 *  Query DB table <tt>busi_type</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from busi_type where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return BusiTypeDO
	 *	@throws DataAccessException
	 */	 
    public BusiTypeDO findById(int id) throws DataAccessException {
        Integer param = new Integer(id);

        return (BusiTypeDO) getSqlMapClientTemplate().queryForObject("MS-BUSI-TYPE-FIND-BY-ID", param);

    }

	/**
	 *  Delete records from DB table <tt>busi_type</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from busi_type where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(int id) throws DataAccessException {
        Integer param = new Integer(id);

        return getSqlMapClientTemplate().delete("MS-BUSI-TYPE-DELETE-BY-ID", param);
    }

	/**
	 *  Query DB table <tt>busi_type</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from busi_type where (1 = 1)</tt>
	 *
	 *	@param busiType
	 *	@param limitStart
	 *	@param pageSize
	 *	@param sortCol
	 *	@param sortOrder
	 *	@return List<BusiTypeDO>
	 *	@throws DataAccessException
	 */	 
    public List<BusiTypeDO> findByCondition(BusiTypeDO busiType, long limitStart, long pageSize, String sortCol, String sortOrder) throws DataAccessException {
    	if (busiType == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}

        Map param = new HashMap();

        param.put("busiType", busiType);
        param.put("limitStart", new Long(limitStart));
        param.put("pageSize", new Long(pageSize));
        param.put("sortCol", sortCol);
        param.put("sortOrder", sortOrder);

        return getSqlMapClientTemplate().queryForList("MS-BUSI-TYPE-FIND-BY-CONDITION", param);

    }

	/**
	 *  Query DB table <tt>busi_type</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from busi_type where (1 = 1)</tt>
	 *
	 *	@param busiType
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(BusiTypeDO busiType) throws DataAccessException {
    	if (busiType == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}


	    Long retObj = (Long) getSqlMapClientTemplate().queryForObject("MS-BUSI-TYPE-FIND-BY-CONDITION-COUNT", busiType);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.longValue();
		}

    }

}