/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.fcs.pm.dal.daointerface.FCapitalAppropriationApplyReceiptDAO;


// auto generated imports
import com.born.fcs.pm.dal.dataobject.FCapitalAppropriationApplyReceiptDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Map;
	import java.util.HashMap;
	
/**
 * An ibatis based implementation of dao interface <tt>com.born.fcs.pm.dal.daointerface.FCapitalAppropriationApplyReceiptDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/f_capital_appropriation_apply_receipt.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 
@SuppressWarnings({ "unchecked", "rawtypes" })

public class IbatisFCapitalAppropriationApplyReceiptDAO extends SqlMapClientDaoSupport implements FCapitalAppropriationApplyReceiptDAO {
	/**
	 *  Insert one <tt>FCapitalAppropriationApplyReceiptDO</tt> object to DB table <tt>f_capital_appropriation_apply_receipt</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into f_capital_appropriation_apply_receipt(form_id,stroke_time,payee_account_name,bank_account,payee_account,payment_amount,attach,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param FCapitalAppropriationApplyReceipt
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(FCapitalAppropriationApplyReceiptDO FCapitalAppropriationApplyReceipt) throws DataAccessException {
    	if (FCapitalAppropriationApplyReceipt == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-F-CAPITAL-APPROPRIATION-APPLY-RECEIPT-INSERT", FCapitalAppropriationApplyReceipt);

        return FCapitalAppropriationApplyReceipt.getId();
    }

	/**
	 *  Update DB table <tt>f_capital_appropriation_apply_receipt</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update f_capital_appropriation_apply_receipt set form_id=?, stroke_time=?, payee_account_name=?, bank_account=?, payee_account=?, payment_amount=?, attach=? where (id = ?)</tt>
	 *
	 *	@param FCapitalAppropriationApplyReceipt
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(FCapitalAppropriationApplyReceiptDO FCapitalAppropriationApplyReceipt) throws DataAccessException {
    	if (FCapitalAppropriationApplyReceipt == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-F-CAPITAL-APPROPRIATION-APPLY-RECEIPT-UPDATE", FCapitalAppropriationApplyReceipt);
    }

	/**
	 *  Query DB table <tt>f_capital_appropriation_apply_receipt</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_capital_appropriation_apply_receipt where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return FCapitalAppropriationApplyReceiptDO
	 *	@throws DataAccessException
	 */	 
    public FCapitalAppropriationApplyReceiptDO findById(long id) throws DataAccessException {
        Long param = new Long(id);

        return (FCapitalAppropriationApplyReceiptDO) getSqlMapClientTemplate().queryForObject("MS-F-CAPITAL-APPROPRIATION-APPLY-RECEIPT-FIND-BY-ID", param);

    }

	/**
	 *  Query DB table <tt>f_capital_appropriation_apply_receipt</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_capital_appropriation_apply_receipt where (form_id = ?)</tt>
	 *
	 *	@param formId
	 *	@return FCapitalAppropriationApplyReceiptDO
	 *	@throws DataAccessException
	 */	 
    public FCapitalAppropriationApplyReceiptDO findByFormId(long formId) throws DataAccessException {
        Long param = new Long(formId);

        return (FCapitalAppropriationApplyReceiptDO) getSqlMapClientTemplate().queryForObject("MS-F-CAPITAL-APPROPRIATION-APPLY-RECEIPT-FIND-BY-FORM-ID", param);

    }

	/**
	 *  Delete records from DB table <tt>f_capital_appropriation_apply_receipt</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_capital_appropriation_apply_receipt where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException {
        Long param = new Long(id);

        return getSqlMapClientTemplate().delete("MS-F-CAPITAL-APPROPRIATION-APPLY-RECEIPT-DELETE-BY-ID", param);
    }

	/**
	 *  Query DB table <tt>f_capital_appropriation_apply_receipt</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_capital_appropriation_apply_receipt where (1 = 1)</tt>
	 *
	 *	@param FCapitalAppropriationApplyReceipt
	 *	@param limitStart
	 *	@param pageSize
	 *	@return List<FCapitalAppropriationApplyReceiptDO>
	 *	@throws DataAccessException
	 */	 
    public List<FCapitalAppropriationApplyReceiptDO> findByCondition(FCapitalAppropriationApplyReceiptDO FCapitalAppropriationApplyReceipt, long limitStart, long pageSize) throws DataAccessException {
    	if (FCapitalAppropriationApplyReceipt == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}

        Map param = new HashMap();

        param.put("FCapitalAppropriationApplyReceipt", FCapitalAppropriationApplyReceipt);
        param.put("limitStart", new Long(limitStart));
        param.put("pageSize", new Long(pageSize));

        return getSqlMapClientTemplate().queryForList("MS-F-CAPITAL-APPROPRIATION-APPLY-RECEIPT-FIND-BY-CONDITION", param);

    }

	/**
	 *  Query DB table <tt>f_capital_appropriation_apply_receipt</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from f_capital_appropriation_apply_receipt where (1 = 1)</tt>
	 *
	 *	@param FCapitalAppropriationApplyReceipt
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(FCapitalAppropriationApplyReceiptDO FCapitalAppropriationApplyReceipt) throws DataAccessException {
    	if (FCapitalAppropriationApplyReceipt == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}


	    Long retObj = (Long) getSqlMapClientTemplate().queryForObject("MS-F-CAPITAL-APPROPRIATION-APPLY-RECEIPT-FIND-BY-CONDITION-COUNT", FCapitalAppropriationApplyReceipt);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.longValue();
		}

    }

}