/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.fcs.pm.dal.daointerface.ProjectRecoveryLitigationPlaceOnFileDAO;


// auto generated imports
import com.born.fcs.pm.dal.dataobject.ProjectRecoveryLitigationPlaceOnFileDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * An ibatis based implementation of dao interface <tt>com.born.fcs.pm.dal.daointerface.ProjectRecoveryLitigationPlaceOnFileDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/project_recovery_litigation_place_on_file.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 
@SuppressWarnings("unchecked")

public class IbatisProjectRecoveryLitigationPlaceOnFileDAO extends SqlMapClientDaoSupport implements ProjectRecoveryLitigationPlaceOnFileDAO {
	/**
	 *  Insert one <tt>ProjectRecoveryLitigationPlaceOnFileDO</tt> object to DB table <tt>project_recovery_litigation_place_on_file</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into project_recovery_litigation_place_on_file(project_recovery_id,accepting_court,agent_law_firm,agent_attorney,agent_judge,place_on_file_time,pay_time,memo,litigation_index,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param projectRecoveryLitigationPlaceOnFile
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(ProjectRecoveryLitigationPlaceOnFileDO projectRecoveryLitigationPlaceOnFile) throws DataAccessException {
    	if (projectRecoveryLitigationPlaceOnFile == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-PROJECT-RECOVERY-LITIGATION-PLACE-ON-FILE-INSERT", projectRecoveryLitigationPlaceOnFile);

        return projectRecoveryLitigationPlaceOnFile.getId();
    }

	/**
	 *  Update DB table <tt>project_recovery_litigation_place_on_file</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update project_recovery_litigation_place_on_file set project_recovery_id=?, accepting_court=?, agent_law_firm=?, agent_attorney=?, agent_judge=?, place_on_file_time=?, pay_time=?, memo=?, litigation_index=? where (id = ?)</tt>
	 *
	 *	@param projectRecoveryLitigationPlaceOnFile
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(ProjectRecoveryLitigationPlaceOnFileDO projectRecoveryLitigationPlaceOnFile) throws DataAccessException {
    	if (projectRecoveryLitigationPlaceOnFile == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-PROJECT-RECOVERY-LITIGATION-PLACE-ON-FILE-UPDATE", projectRecoveryLitigationPlaceOnFile);
    }

	/**
	 *  Query DB table <tt>project_recovery_litigation_place_on_file</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from project_recovery_litigation_place_on_file where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return ProjectRecoveryLitigationPlaceOnFileDO
	 *	@throws DataAccessException
	 */	 
    public ProjectRecoveryLitigationPlaceOnFileDO findById(long id) throws DataAccessException {
        Long param = new Long(id);

        return (ProjectRecoveryLitigationPlaceOnFileDO) getSqlMapClientTemplate().queryForObject("MS-PROJECT-RECOVERY-LITIGATION-PLACE-ON-FILE-FIND-BY-ID", param);

    }

	/**
	 *  Query DB table <tt>project_recovery_litigation_place_on_file</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from project_recovery_litigation_place_on_file where (project_recovery_id = ?)</tt>
	 *
	 *	@param projectRecoveryId
	 *	@return List<ProjectRecoveryLitigationPlaceOnFileDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProjectRecoveryLitigationPlaceOnFileDO> findByRecoveryId(long projectRecoveryId) throws DataAccessException {
        Long param = new Long(projectRecoveryId);

        return getSqlMapClientTemplate().queryForList("MS-PROJECT-RECOVERY-LITIGATION-PLACE-ON-FILE-FIND-BY-RECOVERY-ID", param);

    }

	/**
	 *  Delete records from DB table <tt>project_recovery_litigation_place_on_file</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from project_recovery_litigation_place_on_file where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException {
        Long param = new Long(id);

        return getSqlMapClientTemplate().delete("MS-PROJECT-RECOVERY-LITIGATION-PLACE-ON-FILE-DELETE-BY-ID", param);
    }

	/**
	 *  Delete records from DB table <tt>project_recovery_litigation_place_on_file</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from project_recovery_litigation_place_on_file where (project_recovery_id = ?)</tt>
	 *
	 *	@param projectRecoveryId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByRecoveryId(long projectRecoveryId) throws DataAccessException {
        Long param = new Long(projectRecoveryId);

        return getSqlMapClientTemplate().delete("MS-PROJECT-RECOVERY-LITIGATION-PLACE-ON-FILE-DELETE-BY-RECOVERY-ID", param);
    }

}