/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.fcs.pm.dal.daointerface.FInvestigationMajorEventDAO;


// auto generated imports
import com.born.fcs.pm.dal.dataobject.FInvestigationMajorEventDO;
import org.springframework.dao.DataAccessException;

/**
 * An ibatis based implementation of dao interface <tt>com.born.fcs.pm.dal.daointerface.FInvestigationMajorEventDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/f_investigation_major_events.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 

public class IbatisFInvestigationMajorEventDAO extends SqlMapClientDaoSupport implements FInvestigationMajorEventDAO {
	/**
	 *  Insert one <tt>FInvestigationMajorEventDO</tt> object to DB table <tt>f_investigation_major_events</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into f_investigation_major_events(form_id,project_code,project_name,customer_id,customer_name,financial_condition,investment,other_events,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param FInvestigationMajorEvent
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(FInvestigationMajorEventDO FInvestigationMajorEvent) throws DataAccessException {
    	if (FInvestigationMajorEvent == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-F-INVESTIGATION-MAJOR-EVENT-INSERT", FInvestigationMajorEvent);

        return FInvestigationMajorEvent.getId();
    }

	/**
	 *  Update DB table <tt>f_investigation_major_events</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update f_investigation_major_events set form_id=?, project_code=?, project_name=?, customer_id=?, customer_name=?, financial_condition=?, investment=?, other_events=? where (id = ?)</tt>
	 *
	 *	@param FInvestigationMajorEvent
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(FInvestigationMajorEventDO FInvestigationMajorEvent) throws DataAccessException {
    	if (FInvestigationMajorEvent == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-F-INVESTIGATION-MAJOR-EVENT-UPDATE", FInvestigationMajorEvent);
    }

	/**
	 *  Update DB table <tt>f_investigation_major_events</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update f_investigation_major_events set project_code=?, project_name=?, customer_id=?, customer_name=?, financial_condition=?, investment=?, other_events=? where (form_id = ?)</tt>
	 *
	 *	@param FInvestigationMajorEvent
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateByFormId(FInvestigationMajorEventDO FInvestigationMajorEvent) throws DataAccessException {
    	if (FInvestigationMajorEvent == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-F-INVESTIGATION-MAJOR-EVENT-UPDATE-BY-FORM-ID", FInvestigationMajorEvent);
    }

	/**
	 *  Update DB table <tt>f_investigation_major_events</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update f_investigation_major_events set form_id=?, project_name=?, customer_id=?, customer_name=?, financial_condition=?, investment=?, other_events=? where (project_code = ?)</tt>
	 *
	 *	@param FInvestigationMajorEvent
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateByProjectCode(FInvestigationMajorEventDO FInvestigationMajorEvent) throws DataAccessException {
    	if (FInvestigationMajorEvent == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-F-INVESTIGATION-MAJOR-EVENT-UPDATE-BY-PROJECT-CODE", FInvestigationMajorEvent);
    }

	/**
	 *  Query DB table <tt>f_investigation_major_events</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_investigation_major_events where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return FInvestigationMajorEventDO
	 *	@throws DataAccessException
	 */	 
    public FInvestigationMajorEventDO findById(long id) throws DataAccessException {
        Long param = new Long(id);

        return (FInvestigationMajorEventDO) getSqlMapClientTemplate().queryForObject("MS-F-INVESTIGATION-MAJOR-EVENT-FIND-BY-ID", param);

    }

	/**
	 *  Query DB table <tt>f_investigation_major_events</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_investigation_major_events where (form_id = ?)</tt>
	 *
	 *	@param formId
	 *	@return FInvestigationMajorEventDO
	 *	@throws DataAccessException
	 */	 
    public FInvestigationMajorEventDO findByFormId(long formId) throws DataAccessException {
        Long param = new Long(formId);

        return (FInvestigationMajorEventDO) getSqlMapClientTemplate().queryForObject("MS-F-INVESTIGATION-MAJOR-EVENT-FIND-BY-FORM-ID", param);

    }

	/**
	 *  Query DB table <tt>f_investigation_major_events</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_investigation_major_events where (project_code = ?)</tt>
	 *
	 *	@param projectCode
	 *	@return FInvestigationMajorEventDO
	 *	@throws DataAccessException
	 */	 
    public FInvestigationMajorEventDO findByProjectCode(String projectCode) throws DataAccessException {

        return (FInvestigationMajorEventDO) getSqlMapClientTemplate().queryForObject("MS-F-INVESTIGATION-MAJOR-EVENT-FIND-BY-PROJECT-CODE", projectCode);

    }

	/**
	 *  Delete records from DB table <tt>f_investigation_major_events</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_investigation_major_events where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException {
        Long param = new Long(id);

        return getSqlMapClientTemplate().delete("MS-F-INVESTIGATION-MAJOR-EVENT-DELETE-BY-ID", param);
    }

	/**
	 *  Delete records from DB table <tt>f_investigation_major_events</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_investigation_major_events where (form_id = ?)</tt>
	 *
	 *	@param formId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByFormId(long formId) throws DataAccessException {
        Long param = new Long(formId);

        return getSqlMapClientTemplate().delete("MS-F-INVESTIGATION-MAJOR-EVENT-DELETE-BY-FORM-ID", param);
    }

	/**
	 *  Delete records from DB table <tt>f_investigation_major_events</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_investigation_major_events where (project_code = ?)</tt>
	 *
	 *	@param projectCode
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByProjectCode(String projectCode) throws DataAccessException {

        return getSqlMapClientTemplate().delete("MS-F-INVESTIGATION-MAJOR-EVENT-DELETE-BY-PROJECT-CODE", projectCode);
    }

}