/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.fcs.pm.dal.daointerface.ShortMessageDAO;


// auto generated imports
import com.born.fcs.pm.dal.dataobject.ShortMessageDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Map;
	import java.util.HashMap;
	
/**
 * An ibatis based implementation of dao interface <tt>com.born.fcs.pm.dal.daointerface.ShortMessageDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/short_message.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 
@SuppressWarnings({ "unchecked", "rawtypes" })

public class IbatisShortMessageDAO extends SqlMapClientDaoSupport implements ShortMessageDAO {
	/**
	 *  Insert one <tt>ShortMessageDO</tt> object to DB table <tt>short_message</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into short_message(message_sender_id,message_sender_name,message_sender_account,message_receiver,message_content,raw_add_time) values (?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param shortMessage
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(ShortMessageDO shortMessage) throws DataAccessException {
    	if (shortMessage == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-SHORT-MESSAGE-INSERT", shortMessage);

        return shortMessage.getId();
    }

	/**
	 *  Update DB table <tt>short_message</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update short_message set message_sender_id=?, message_sender_name=?, message_sender_account=?, message_receiver=?, message_content=? where (id = ?)</tt>
	 *
	 *	@param shortMessage
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(ShortMessageDO shortMessage) throws DataAccessException {
    	if (shortMessage == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-SHORT-MESSAGE-UPDATE", shortMessage);
    }

	/**
	 *  Query DB table <tt>short_message</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from short_message where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return ShortMessageDO
	 *	@throws DataAccessException
	 */	 
    public ShortMessageDO findById(long id) throws DataAccessException {
        Long param = new Long(id);

        return (ShortMessageDO) getSqlMapClientTemplate().queryForObject("MS-SHORT-MESSAGE-FIND-BY-ID", param);

    }

	/**
	 *  Delete records from DB table <tt>short_message</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from short_message where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException {
        Long param = new Long(id);

        return getSqlMapClientTemplate().delete("MS-SHORT-MESSAGE-DELETE-BY-ID", param);
    }

	/**
	 *  Query DB table <tt>short_message</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from short_message where (1 = 1)</tt>
	 *
	 *	@param shortMessage
	 *	@param limitStart
	 *	@param pageSize
	 *	@param beginMessageSendDate
	 *	@param endMessageSendDate
	 *	@return List<ShortMessageDO>
	 *	@throws DataAccessException
	 */	 
    public List<ShortMessageDO> findByCondition(ShortMessageDO shortMessage, long limitStart, long pageSize, String beginMessageSendDate, String endMessageSendDate) throws DataAccessException {
    	if (shortMessage == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}

        Map param = new HashMap();

        param.put("shortMessage", shortMessage);
        param.put("limitStart", new Long(limitStart));
        param.put("pageSize", new Long(pageSize));
        param.put("beginMessageSendDate", beginMessageSendDate);
        param.put("endMessageSendDate", endMessageSendDate);

        return getSqlMapClientTemplate().queryForList("MS-SHORT-MESSAGE-FIND-BY-CONDITION", param);

    }

	/**
	 *  Query DB table <tt>short_message</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from short_message where (1 = 1)</tt>
	 *
	 *	@param shortMessage
	 *	@param beginMessageSendDate
	 *	@param endMessageSendDate
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(ShortMessageDO shortMessage, String beginMessageSendDate, String endMessageSendDate) throws DataAccessException {
    	if (shortMessage == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}

        Map param = new HashMap();

        param.put("shortMessage", shortMessage);
        param.put("beginMessageSendDate", beginMessageSendDate);
        param.put("endMessageSendDate", endMessageSendDate);

	    Long retObj = (Long) getSqlMapClientTemplate().queryForObject("MS-SHORT-MESSAGE-FIND-BY-CONDITION-COUNT", param);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.longValue();
		}

    }

}