/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.fcs.pm.dal.daointerface.FInvestigationMainlyReviewRelatedCompanyDAO;


// auto generated imports
import com.born.fcs.pm.dal.dataobject.FInvestigationMainlyReviewRelatedCompanyDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * An ibatis based implementation of dao interface <tt>com.born.fcs.pm.dal.daointerface.FInvestigationMainlyReviewRelatedCompanyDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/f_investigation_mainly_review_related_company.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 
@SuppressWarnings("unchecked")

public class IbatisFInvestigationMainlyReviewRelatedCompanyDAO extends SqlMapClientDaoSupport implements FInvestigationMainlyReviewRelatedCompanyDAO {
	/**
	 *  Insert one <tt>FInvestigationMainlyReviewRelatedCompanyDO</tt> object to DB table <tt>f_investigation_mainly_review_related_company</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into f_investigation_mainly_review_related_company(m_review_id,relation,relation_desc,company_name,register_capital,capital_ratio,major_busi,asset_scale,asset_liability_ratio,net_profit_this_year,net_profit_last_year,sort_order,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param FInvestigationMainlyReviewRelatedCompany
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(FInvestigationMainlyReviewRelatedCompanyDO FInvestigationMainlyReviewRelatedCompany) throws DataAccessException {
    	if (FInvestigationMainlyReviewRelatedCompany == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-F-INVESTIGATION-MAINLY-REVIEW-RELATED-COMPANY-INSERT", FInvestigationMainlyReviewRelatedCompany);

        return FInvestigationMainlyReviewRelatedCompany.getId();
    }

	/**
	 *  Update DB table <tt>f_investigation_mainly_review_related_company</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update f_investigation_mainly_review_related_company set m_review_id=?, relation=?, relation_desc=?, company_name=?, register_capital=?, capital_ratio=?, major_busi=?, asset_scale=?, asset_liability_ratio=?, net_profit_this_year=?, net_profit_last_year=?, sort_order=? where (id = ?)</tt>
	 *
	 *	@param FInvestigationMainlyReviewRelatedCompany
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(FInvestigationMainlyReviewRelatedCompanyDO FInvestigationMainlyReviewRelatedCompany) throws DataAccessException {
    	if (FInvestigationMainlyReviewRelatedCompany == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-F-INVESTIGATION-MAINLY-REVIEW-RELATED-COMPANY-UPDATE", FInvestigationMainlyReviewRelatedCompany);
    }

	/**
	 *  Query DB table <tt>f_investigation_mainly_review_related_company</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_investigation_mainly_review_related_company where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return FInvestigationMainlyReviewRelatedCompanyDO
	 *	@throws DataAccessException
	 */	 
    public FInvestigationMainlyReviewRelatedCompanyDO findById(long id) throws DataAccessException {
        Long param = new Long(id);

        return (FInvestigationMainlyReviewRelatedCompanyDO) getSqlMapClientTemplate().queryForObject("MS-F-INVESTIGATION-MAINLY-REVIEW-RELATED-COMPANY-FIND-BY-ID", param);

    }

	/**
	 *  Query DB table <tt>f_investigation_mainly_review_related_company</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_investigation_mainly_review_related_company where (m_review_id = ?) order by sort_order ASC</tt>
	 *
	 *	@param MReviewId
	 *	@return List<FInvestigationMainlyReviewRelatedCompanyDO>
	 *	@throws DataAccessException
	 */	 
    public List<FInvestigationMainlyReviewRelatedCompanyDO> findByReviewId(long MReviewId) throws DataAccessException {
        Long param = new Long(MReviewId);

        return getSqlMapClientTemplate().queryForList("MS-F-INVESTIGATION-MAINLY-REVIEW-RELATED-COMPANY-FIND-BY-REVIEW-ID", param);

    }

	/**
	 *  Query DB table <tt>f_investigation_mainly_review_related_company</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_investigation_mainly_review_related_company where (relation = ?) order by sort_order ASC</tt>
	 *
	 *	@param relation
	 *	@return List<FInvestigationMainlyReviewRelatedCompanyDO>
	 *	@throws DataAccessException
	 */	 
    public List<FInvestigationMainlyReviewRelatedCompanyDO> findByRelation(String relation) throws DataAccessException {

        return getSqlMapClientTemplate().queryForList("MS-F-INVESTIGATION-MAINLY-REVIEW-RELATED-COMPANY-FIND-BY-RELATION", relation);

    }

	/**
	 *  Delete records from DB table <tt>f_investigation_mainly_review_related_company</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_investigation_mainly_review_related_company where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException {
        Long param = new Long(id);

        return getSqlMapClientTemplate().delete("MS-F-INVESTIGATION-MAINLY-REVIEW-RELATED-COMPANY-DELETE-BY-ID", param);
    }

	/**
	 *  Delete records from DB table <tt>f_investigation_mainly_review_related_company</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_investigation_mainly_review_related_company where (m_review_id = ?)</tt>
	 *
	 *	@param MReviewId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByReviewId(long MReviewId) throws DataAccessException {
        Long param = new Long(MReviewId);

        return getSqlMapClientTemplate().delete("MS-F-INVESTIGATION-MAINLY-REVIEW-RELATED-COMPANY-DELETE-BY-REVIEW-ID", param);
    }

	/**
	 *  Delete records from DB table <tt>f_investigation_mainly_review_related_company</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_investigation_mainly_review_related_company where (relation = ?)</tt>
	 *
	 *	@param relation
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByRelation(String relation) throws DataAccessException {

        return getSqlMapClientTemplate().delete("MS-F-INVESTIGATION-MAINLY-REVIEW-RELATED-COMPANY-DELETE-BY-RELATION", relation);
    }

}