/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.fcs.pm.dal.daointerface.FCapitalAppropriationApplyFeeDAO;


// auto generated imports
import com.born.fcs.pm.dal.dataobject.FCapitalAppropriationApplyFeeDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Map;
	import java.util.HashMap;
	
/**
 * An ibatis based implementation of dao interface <tt>com.born.fcs.pm.dal.daointerface.FCapitalAppropriationApplyFeeDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/f_capital_appropriation_apply_fee.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 
@SuppressWarnings({ "unchecked", "rawtypes" })

public class IbatisFCapitalAppropriationApplyFeeDAO extends SqlMapClientDaoSupport implements FCapitalAppropriationApplyFeeDAO {
	/**
	 *  Insert one <tt>FCapitalAppropriationApplyFeeDO</tt> object to DB table <tt>f_capital_appropriation_apply_fee</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into f_capital_appropriation_apply_fee(apply_id,appropriate_reason,appropriate_amount,com_type,remark,form_change,risk_council_summary,project_approval,finance_affirm_detail_id,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param FCapitalAppropriationApplyFee
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(FCapitalAppropriationApplyFeeDO FCapitalAppropriationApplyFee) throws DataAccessException {
    	if (FCapitalAppropriationApplyFee == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-F-CAPITAL-APPROPRIATION-APPLY-FEE-INSERT", FCapitalAppropriationApplyFee);

        return FCapitalAppropriationApplyFee.getId();
    }

	/**
	 *  Update DB table <tt>f_capital_appropriation_apply_fee</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update f_capital_appropriation_apply_fee set apply_id=?, appropriate_reason=?, appropriate_amount=?, com_type=?, remark=?, form_change=?, risk_council_summary=?, project_approval=?, finance_affirm_detail_id=? where (id = ?)</tt>
	 *
	 *	@param FCapitalAppropriationApplyFee
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(FCapitalAppropriationApplyFeeDO FCapitalAppropriationApplyFee) throws DataAccessException {
    	if (FCapitalAppropriationApplyFee == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-F-CAPITAL-APPROPRIATION-APPLY-FEE-UPDATE", FCapitalAppropriationApplyFee);
    }

	/**
	 *  Query DB table <tt>f_capital_appropriation_apply_fee</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_capital_appropriation_apply_fee where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return FCapitalAppropriationApplyFeeDO
	 *	@throws DataAccessException
	 */	 
    public FCapitalAppropriationApplyFeeDO findById(long id) throws DataAccessException {
        Long param = new Long(id);

        return (FCapitalAppropriationApplyFeeDO) getSqlMapClientTemplate().queryForObject("MS-F-CAPITAL-APPROPRIATION-APPLY-FEE-FIND-BY-ID", param);

    }

	/**
	 *  Query DB table <tt>f_capital_appropriation_apply_fee</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_capital_appropriation_apply_fee where (apply_id = ?)</tt>
	 *
	 *	@param applyId
	 *	@return List<FCapitalAppropriationApplyFeeDO>
	 *	@throws DataAccessException
	 */	 
    public List<FCapitalAppropriationApplyFeeDO> findByApplyId(long applyId) throws DataAccessException {
        Long param = new Long(applyId);

        return getSqlMapClientTemplate().queryForList("MS-F-CAPITAL-APPROPRIATION-APPLY-FEE-FIND-BY-APPLY-ID", param);

    }

	/**
	 *  Delete records from DB table <tt>f_capital_appropriation_apply_fee</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_capital_appropriation_apply_fee where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException {
        Long param = new Long(id);

        return getSqlMapClientTemplate().delete("MS-F-CAPITAL-APPROPRIATION-APPLY-FEE-DELETE-BY-ID", param);
    }

	/**
	 *  Delete records from DB table <tt>f_capital_appropriation_apply_fee</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_capital_appropriation_apply_fee where (apply_id = ?)</tt>
	 *
	 *	@param applyId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByApplyId(long applyId) throws DataAccessException {
        Long param = new Long(applyId);

        return getSqlMapClientTemplate().delete("MS-F-CAPITAL-APPROPRIATION-APPLY-FEE-DELETE-BY-APPLY-ID", param);
    }

	/**
	 *  Query DB table <tt>f_capital_appropriation_apply_fee</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_capital_appropriation_apply_fee where (1 = 1)</tt>
	 *
	 *	@param FCapitalAppropriationApplyFee
	 *	@param limitStart
	 *	@param pageSize
	 *	@return List<FCapitalAppropriationApplyFeeDO>
	 *	@throws DataAccessException
	 */	 
    public List<FCapitalAppropriationApplyFeeDO> findByCondition(FCapitalAppropriationApplyFeeDO FCapitalAppropriationApplyFee, long limitStart, long pageSize) throws DataAccessException {
    	if (FCapitalAppropriationApplyFee == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}

        Map param = new HashMap();

        param.put("FCapitalAppropriationApplyFee", FCapitalAppropriationApplyFee);
        param.put("limitStart", new Long(limitStart));
        param.put("pageSize", new Long(pageSize));

        return getSqlMapClientTemplate().queryForList("MS-F-CAPITAL-APPROPRIATION-APPLY-FEE-FIND-BY-CONDITION", param);

    }

	/**
	 *  Query DB table <tt>f_capital_appropriation_apply_fee</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from f_capital_appropriation_apply_fee where (1 = 1)</tt>
	 *
	 *	@param FCapitalAppropriationApplyFee
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(FCapitalAppropriationApplyFeeDO FCapitalAppropriationApplyFee) throws DataAccessException {
    	if (FCapitalAppropriationApplyFee == null) {
    		throw new IllegalArgumentException("Can't select by a null data object.");
    	}


	    Long retObj = (Long) getSqlMapClientTemplate().queryForObject("MS-F-CAPITAL-APPROPRIATION-APPLY-FEE-FIND-BY-CONDITION-COUNT", FCapitalAppropriationApplyFee);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.longValue();
		}

    }

}