/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.fcs.pm.dal.daointerface.FAfterwardsCheckReportItemDAO;


// auto generated imports
import com.born.fcs.pm.dal.dataobject.FAfterwardsCheckReportItemDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Map;
	import java.util.HashMap;
	
/**
 * An ibatis based implementation of dao interface <tt>com.born.fcs.pm.dal.daointerface.FAfterwardsCheckReportItemDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/f_afterwards_check_report_item.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 
@SuppressWarnings({ "unchecked", "rawtypes" })

public class IbatisFAfterwardsCheckReportItemDAO extends SqlMapClientDaoSupport implements FAfterwardsCheckReportItemDAO {
	/**
	 *  Insert one <tt>FAfterwardsCheckReportItemDO</tt> object to DB table <tt>f_afterwards_check_report_item</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into f_afterwards_check_report_item(form_id,item_type,item_name,item_value1,item_value2,item_value3,item_desc,del_able,sort_order,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param FAfterwardsCheckReportItem
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(FAfterwardsCheckReportItemDO FAfterwardsCheckReportItem) throws DataAccessException {
    	if (FAfterwardsCheckReportItem == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-F-AFTERWARDS-CHECK-REPORT-ITEM-INSERT", FAfterwardsCheckReportItem);

        return FAfterwardsCheckReportItem.getItemId();
    }

	/**
	 *  Update DB table <tt>f_afterwards_check_report_item</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update f_afterwards_check_report_item set form_id=?, item_type=?, item_name=?, item_value1=?, item_value2=?, item_value3=?, item_desc=?, del_able=?, sort_order=? where (item_id = ?)</tt>
	 *
	 *	@param FAfterwardsCheckReportItem
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(FAfterwardsCheckReportItemDO FAfterwardsCheckReportItem) throws DataAccessException {
    	if (FAfterwardsCheckReportItem == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-F-AFTERWARDS-CHECK-REPORT-ITEM-UPDATE", FAfterwardsCheckReportItem);
    }

	/**
	 *  Query DB table <tt>f_afterwards_check_report_item</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_afterwards_check_report_item where (item_id = ?)</tt>
	 *
	 *	@param itemId
	 *	@return FAfterwardsCheckReportItemDO
	 *	@throws DataAccessException
	 */	 
    public FAfterwardsCheckReportItemDO findById(long itemId) throws DataAccessException {
        Long param = new Long(itemId);

        return (FAfterwardsCheckReportItemDO) getSqlMapClientTemplate().queryForObject("MS-F-AFTERWARDS-CHECK-REPORT-ITEM-FIND-BY-ID", param);

    }

	/**
	 *  Query DB table <tt>f_afterwards_check_report_item</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_afterwards_check_report_item where (form_id = ?) order by sort_order ASC</tt>
	 *
	 *	@param formId
	 *	@return List<FAfterwardsCheckReportItemDO>
	 *	@throws DataAccessException
	 */	 
    public List<FAfterwardsCheckReportItemDO> findByFormId(long formId) throws DataAccessException {
        Long param = new Long(formId);

        return getSqlMapClientTemplate().queryForList("MS-F-AFTERWARDS-CHECK-REPORT-ITEM-FIND-BY-FORM-ID", param);

    }

	/**
	 *  Query DB table <tt>f_afterwards_check_report_item</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_afterwards_check_report_item where ((form_id = ?) AND (item_type = ?)) order by sort_order ASC</tt>
	 *
	 *	@param formId
	 *	@param itemType
	 *	@return List<FAfterwardsCheckReportItemDO>
	 *	@throws DataAccessException
	 */	 
    public List<FAfterwardsCheckReportItemDO> findByFormIdAndItemType(long formId, String itemType) throws DataAccessException {
        Map param = new HashMap();

        param.put("formId", new Long(formId));
        param.put("itemType", itemType);

        return getSqlMapClientTemplate().queryForList("MS-F-AFTERWARDS-CHECK-REPORT-ITEM-FIND-BY-FORM-ID-AND-ITEM-TYPE", param);

    }

	/**
	 *  Delete records from DB table <tt>f_afterwards_check_report_item</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_afterwards_check_report_item where (item_id = ?)</tt>
	 *
	 *	@param itemId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long itemId) throws DataAccessException {
        Long param = new Long(itemId);

        return getSqlMapClientTemplate().delete("MS-F-AFTERWARDS-CHECK-REPORT-ITEM-DELETE-BY-ID", param);
    }

	/**
	 *  Delete records from DB table <tt>f_afterwards_check_report_item</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_afterwards_check_report_item where (form_id = ?)</tt>
	 *
	 *	@param formId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByFormId(long formId) throws DataAccessException {
        Long param = new Long(formId);

        return getSqlMapClientTemplate().delete("MS-F-AFTERWARDS-CHECK-REPORT-ITEM-DELETE-BY-FORM-ID", param);
    }

	/**
	 *  Delete records from DB table <tt>f_afterwards_check_report_item</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_afterwards_check_report_item where ((form_id = ?) AND (item_type = ?))</tt>
	 *
	 *	@param formId
	 *	@param itemType
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByFormIdAndItemType(long formId, String itemType) throws DataAccessException {
        Map param = new HashMap();

        param.put("formId", new Long(formId));
        param.put("itemType", itemType);

        return getSqlMapClientTemplate().delete("MS-F-AFTERWARDS-CHECK-REPORT-ITEM-DELETE-BY-FORM-ID-AND-ITEM-TYPE", param);
    }

}