/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.fm.dal.daointerface;

// auto generated imports
import com.born.fcs.fm.dal.dataobject.CostCategoryDO;
import org.springframework.dao.DataAccessException;
import com.born.fcs.fm.dal.queryCondition.CostCategoryQueryCondition;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>cost_category</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cost_category.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
 @SuppressWarnings("rawtypes") 
public interface CostCategoryDAO {
	/**
	 *  Insert one <tt>CostCategoryDO</tt> object to DB table <tt>cost_category</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into cost_category(category_id,name,account_code,account_name,used,status,raw_add_time) values (?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param costCategory
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(CostCategoryDO costCategory) throws DataAccessException;

	/**
	 *  Update DB table <tt>cost_category</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update cost_category set name=?, account_code=?, account_name=?, used=?, status=? where (category_id = ?)</tt>
	 *
	 *	@param costCategory
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(CostCategoryDO costCategory) throws DataAccessException;

	/**
	 *  Query DB table <tt>cost_category</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select category_id, name, account_code, account_name, used, status, raw_add_time, raw_update_time from cost_category where (category_id = ?)</tt>
	 *
	 *	@param categoryId
	 *	@return CostCategoryDO
	 *	@throws DataAccessException
	 */	 
    public CostCategoryDO findById(long categoryId) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>cost_category</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from cost_category where (category_id = ?)</tt>
	 *
	 *	@param categoryId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long categoryId) throws DataAccessException;

	/**
	 *  Query DB table <tt>cost_category</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select category_id, name, account_code, account_name, used, status, raw_add_time, raw_update_time from cost_category where (1 = 1)</tt>
	 *
	 *	@param condition
	 *	@return List<CostCategoryDO>
	 *	@throws DataAccessException
	 */	 
    public List<CostCategoryDO> findByCondition(CostCategoryQueryCondition condition) throws DataAccessException;

	/**
	 *  Query DB table <tt>cost_category</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from cost_category where (1 = 1)</tt>
	 *
	 *	@param condition
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(CostCategoryQueryCondition condition) throws DataAccessException;

}