/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.fm.dal.daointerface;

// auto generated imports
import com.born.fcs.fm.dal.dataobject.FormPaymentFeeDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>form_payment_fee</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/form_payment_fee.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
 @SuppressWarnings("rawtypes") 
public interface FormPaymentFeeDAO {
	/**
	 *  Insert one <tt>FormPaymentFeeDO</tt> object to DB table <tt>form_payment_fee</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into form_payment_fee(form_payment_id,form_id,fee_type,amount,payment_account,receipt_account,receipt_name,bank_name,at_code,at_name,payment_date,remark,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param formPaymentFee
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(FormPaymentFeeDO formPaymentFee) throws DataAccessException;

	/**
	 *  Update DB table <tt>form_payment_fee</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update form_payment_fee set form_payment_id=?, form_id=?, fee_type=?, amount=?, payment_account=?, receipt_account=?, receipt_name=?, bank_name=?, at_code=?, at_name=?, payment_date=?, remark=? where (id = ?)</tt>
	 *
	 *	@param formPaymentFee
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(FormPaymentFeeDO formPaymentFee) throws DataAccessException;

	/**
	 *  Query DB table <tt>form_payment_fee</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from form_payment_fee where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return FormPaymentFeeDO
	 *	@throws DataAccessException
	 */	 
    public FormPaymentFeeDO findById(long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>form_payment_fee</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from form_payment_fee where (form_id = ?)</tt>
	 *
	 *	@param formId
	 *	@return List<FormPaymentFeeDO>
	 *	@throws DataAccessException
	 */	 
    public List<FormPaymentFeeDO> findByFormId(long formId) throws DataAccessException;

	/**
	 *  Query DB table <tt>form_payment_fee</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from form_payment_fee f where (payment_account = ?)</tt>
	 *
	 *	@param paymentAccount
	 *	@return List<FormPaymentFeeDO>
	 *	@throws DataAccessException
	 */	 
    public List<FormPaymentFeeDO> findByPaymentAccount(String paymentAccount) throws DataAccessException;

	/**
	 *  Query DB table <tt>form_payment_fee</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from form_payment_fee f where (receipt_account = ?)</tt>
	 *
	 *	@param receiptAccount
	 *	@return List<FormPaymentFeeDO>
	 *	@throws DataAccessException
	 */	 
    public List<FormPaymentFeeDO> findByReceiptAccount(String receiptAccount) throws DataAccessException;

	/**
	 *  Query DB table <tt>form_payment_fee</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from form_payment_fee where (form_payment_id = ?)</tt>
	 *
	 *	@param formPaymentId
	 *	@return List<FormPaymentFeeDO>
	 *	@throws DataAccessException
	 */	 
    public List<FormPaymentFeeDO> findByFormPaymentId(long formPaymentId) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>form_payment_fee</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from form_payment_fee where (form_id = ?)</tt>
	 *
	 *	@param formId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByFormId(long formId) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>form_payment_fee</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from form_payment_fee where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>form_payment_fee</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from form_payment_fee where (1 = 1)</tt>
	 *
	 *	@param formPaymentFee
	 *	@param limitStart
	 *	@param pageSize
	 *	@return List<FormPaymentFeeDO>
	 *	@throws DataAccessException
	 */	 
    public List<FormPaymentFeeDO> findByCondition(FormPaymentFeeDO formPaymentFee, long limitStart, long pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>form_payment_fee</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from form_payment_fee where (1 = 1)</tt>
	 *
	 *	@param formPaymentFee
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(FormPaymentFeeDO formPaymentFee) throws DataAccessException;

}