/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.dataobject;

import java.io.Serializable;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

// auto generated imports
import java.util.Date;

/**
 * A data object class directly models database table <tt>enterprise_scale_rule</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/enterprise_scale_rule.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
public class EnterpriseScaleRuleDO implements Serializable{
	/** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========

	private int ruleId;

	private String industryCode;

	private String industryName;

	private String kpiType;

	private String kpiName;

	private String kpiUnit;

	private String kpiVariable;

	private String scaleHugeScript;

	private String scaleBigScript;

	private String scaleMediumScript;

	private String scaleSmallScript;

	private String scaleTinyScript;

	private String version;

	private Date rawAddTime;

	private Date rawUpdateTime;

    //========== getters and setters ==========

	public int getRuleId() {
		return ruleId;
	}
	
	public void setRuleId(int ruleId) {
		this.ruleId = ruleId;
	}

	public String getIndustryCode() {
		return industryCode;
	}
	
	public void setIndustryCode(String industryCode) {
		this.industryCode = industryCode;
	}

	public String getIndustryName() {
		return industryName;
	}
	
	public void setIndustryName(String industryName) {
		this.industryName = industryName;
	}

	public String getKpiType() {
		return kpiType;
	}
	
	public void setKpiType(String kpiType) {
		this.kpiType = kpiType;
	}

	public String getKpiName() {
		return kpiName;
	}
	
	public void setKpiName(String kpiName) {
		this.kpiName = kpiName;
	}

	public String getKpiUnit() {
		return kpiUnit;
	}
	
	public void setKpiUnit(String kpiUnit) {
		this.kpiUnit = kpiUnit;
	}

	public String getKpiVariable() {
		return kpiVariable;
	}
	
	public void setKpiVariable(String kpiVariable) {
		this.kpiVariable = kpiVariable;
	}

	public String getScaleHugeScript() {
		return scaleHugeScript;
	}
	
	public void setScaleHugeScript(String scaleHugeScript) {
		this.scaleHugeScript = scaleHugeScript;
	}

	public String getScaleBigScript() {
		return scaleBigScript;
	}
	
	public void setScaleBigScript(String scaleBigScript) {
		this.scaleBigScript = scaleBigScript;
	}

	public String getScaleMediumScript() {
		return scaleMediumScript;
	}
	
	public void setScaleMediumScript(String scaleMediumScript) {
		this.scaleMediumScript = scaleMediumScript;
	}

	public String getScaleSmallScript() {
		return scaleSmallScript;
	}
	
	public void setScaleSmallScript(String scaleSmallScript) {
		this.scaleSmallScript = scaleSmallScript;
	}

	public String getScaleTinyScript() {
		return scaleTinyScript;
	}
	
	public void setScaleTinyScript(String scaleTinyScript) {
		this.scaleTinyScript = scaleTinyScript;
	}

	public String getVersion() {
		return version;
	}
	
	public void setVersion(String version) {
		this.version = version;
	}

	public Date getRawAddTime() {
		return rawAddTime;
	}
	
	public void setRawAddTime(Date rawAddTime) {
		this.rawAddTime = rawAddTime;
	}

	public Date getRawUpdateTime() {
		return rawUpdateTime;
	}
	
	public void setRawUpdateTime(Date rawUpdateTime) {
		this.rawUpdateTime = rawUpdateTime;
	}


	/**
     * @return
     *
     * @see java.lang.Object#toString()
     */
	@Override
    public String toString() {

        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
