/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.dataobject;

import java.io.Serializable;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

// auto generated imports
import java.util.Date;
import com.yjf.common.lang.util.money.Money;

/**
 * A data object class directly models database table <tt>project_financial</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/project_financial.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
public class ProjectFinancialDO implements Serializable{
	/** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========

	private long projectId;

	private String projectCode;

	private String originalCode;

	private long productId;

	private String productType;

	private String productName;

	private String termType;

	private String interestType;

	private int timeLimit;

	private String timeUnit;

	private String issueInstitution;

	private double interestRate;

	private String interestSettlementWay;

	private Date expectBuyDate;

	private Date expectExpireDate;

	private Money price = new Money(0, 0);

	private double expectBuyNum;

	private String riskLevel;

	private String riskMeasure;

	private long createUserId;

	private String createUserAccount;

	private String createUserName;

	private long deptId;

	private String deptCode;

	private String deptName;

	private String deptPath;

	private String deptPathName;

	private Date actualBuyDate;

	private Date actualExpireDate;

	private Date cycleExpireDate;

	private Money actualPrice = new Money(0, 0);

	private double actualBuyNum;

	private double originalHoldNum;

	private double actualHoldNum;

	private Money actualPrincipal = new Money(0, 0);

	private Money actualInterest = new Money(0, 0);

	private double actualInterestRate;

	private Money settlementAmount = new Money(0, 0);

	private String canRedeem;

	private String isRoll;

	private String isOpen;

	private int yearDayNum;

	private double transferedNum;

	private double buyBackNum;

	private double redeemedNum;

	private Date preFinishTime;

	private String status;

	private Date rawAddTime;

	private Date rawUpdateTime;

    //========== getters and setters ==========

	public long getProjectId() {
		return projectId;
	}
	
	public void setProjectId(long projectId) {
		this.projectId = projectId;
	}

	public String getProjectCode() {
		return projectCode;
	}
	
	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode;
	}

	public String getOriginalCode() {
		return originalCode;
	}
	
	public void setOriginalCode(String originalCode) {
		this.originalCode = originalCode;
	}

	public long getProductId() {
		return productId;
	}
	
	public void setProductId(long productId) {
		this.productId = productId;
	}

	public String getProductType() {
		return productType;
	}
	
	public void setProductType(String productType) {
		this.productType = productType;
	}

	public String getProductName() {
		return productName;
	}
	
	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getTermType() {
		return termType;
	}
	
	public void setTermType(String termType) {
		this.termType = termType;
	}

	public String getInterestType() {
		return interestType;
	}
	
	public void setInterestType(String interestType) {
		this.interestType = interestType;
	}

	public int getTimeLimit() {
		return timeLimit;
	}
	
	public void setTimeLimit(int timeLimit) {
		this.timeLimit = timeLimit;
	}

	public String getTimeUnit() {
		return timeUnit;
	}
	
	public void setTimeUnit(String timeUnit) {
		this.timeUnit = timeUnit;
	}

	public String getIssueInstitution() {
		return issueInstitution;
	}
	
	public void setIssueInstitution(String issueInstitution) {
		this.issueInstitution = issueInstitution;
	}

	public double getInterestRate() {
		return interestRate;
	}
	
	public void setInterestRate(double interestRate) {
		this.interestRate = interestRate;
	}

	public String getInterestSettlementWay() {
		return interestSettlementWay;
	}
	
	public void setInterestSettlementWay(String interestSettlementWay) {
		this.interestSettlementWay = interestSettlementWay;
	}

	public Date getExpectBuyDate() {
		return expectBuyDate;
	}
	
	public void setExpectBuyDate(Date expectBuyDate) {
		this.expectBuyDate = expectBuyDate;
	}

	public Date getExpectExpireDate() {
		return expectExpireDate;
	}
	
	public void setExpectExpireDate(Date expectExpireDate) {
		this.expectExpireDate = expectExpireDate;
	}

	public Money getPrice() {
		return price;
	}
	
	public void setPrice(Money price) {
		if (price == null) {
			this.price = new Money(0, 0);
		} else {
			this.price = price;
		}
	}

	public double getExpectBuyNum() {
		return expectBuyNum;
	}
	
	public void setExpectBuyNum(double expectBuyNum) {
		this.expectBuyNum = expectBuyNum;
	}

	public String getRiskLevel() {
		return riskLevel;
	}
	
	public void setRiskLevel(String riskLevel) {
		this.riskLevel = riskLevel;
	}

	public String getRiskMeasure() {
		return riskMeasure;
	}
	
	public void setRiskMeasure(String riskMeasure) {
		this.riskMeasure = riskMeasure;
	}

	public long getCreateUserId() {
		return createUserId;
	}
	
	public void setCreateUserId(long createUserId) {
		this.createUserId = createUserId;
	}

	public String getCreateUserAccount() {
		return createUserAccount;
	}
	
	public void setCreateUserAccount(String createUserAccount) {
		this.createUserAccount = createUserAccount;
	}

	public String getCreateUserName() {
		return createUserName;
	}
	
	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}

	public long getDeptId() {
		return deptId;
	}
	
	public void setDeptId(long deptId) {
		this.deptId = deptId;
	}

	public String getDeptCode() {
		return deptCode;
	}
	
	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	public String getDeptName() {
		return deptName;
	}
	
	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getDeptPath() {
		return deptPath;
	}
	
	public void setDeptPath(String deptPath) {
		this.deptPath = deptPath;
	}

	public String getDeptPathName() {
		return deptPathName;
	}
	
	public void setDeptPathName(String deptPathName) {
		this.deptPathName = deptPathName;
	}

	public Date getActualBuyDate() {
		return actualBuyDate;
	}
	
	public void setActualBuyDate(Date actualBuyDate) {
		this.actualBuyDate = actualBuyDate;
	}

	public Date getActualExpireDate() {
		return actualExpireDate;
	}
	
	public void setActualExpireDate(Date actualExpireDate) {
		this.actualExpireDate = actualExpireDate;
	}

	public Date getCycleExpireDate() {
		return cycleExpireDate;
	}
	
	public void setCycleExpireDate(Date cycleExpireDate) {
		this.cycleExpireDate = cycleExpireDate;
	}

	public Money getActualPrice() {
		return actualPrice;
	}
	
	public void setActualPrice(Money actualPrice) {
		if (actualPrice == null) {
			this.actualPrice = new Money(0, 0);
		} else {
			this.actualPrice = actualPrice;
		}
	}

	public double getActualBuyNum() {
		return actualBuyNum;
	}
	
	public void setActualBuyNum(double actualBuyNum) {
		this.actualBuyNum = actualBuyNum;
	}

	public double getOriginalHoldNum() {
		return originalHoldNum;
	}
	
	public void setOriginalHoldNum(double originalHoldNum) {
		this.originalHoldNum = originalHoldNum;
	}

	public double getActualHoldNum() {
		return actualHoldNum;
	}
	
	public void setActualHoldNum(double actualHoldNum) {
		this.actualHoldNum = actualHoldNum;
	}

	public Money getActualPrincipal() {
		return actualPrincipal;
	}
	
	public void setActualPrincipal(Money actualPrincipal) {
		if (actualPrincipal == null) {
			this.actualPrincipal = new Money(0, 0);
		} else {
			this.actualPrincipal = actualPrincipal;
		}
	}

	public Money getActualInterest() {
		return actualInterest;
	}
	
	public void setActualInterest(Money actualInterest) {
		if (actualInterest == null) {
			this.actualInterest = new Money(0, 0);
		} else {
			this.actualInterest = actualInterest;
		}
	}

	public double getActualInterestRate() {
		return actualInterestRate;
	}
	
	public void setActualInterestRate(double actualInterestRate) {
		this.actualInterestRate = actualInterestRate;
	}

	public Money getSettlementAmount() {
		return settlementAmount;
	}
	
	public void setSettlementAmount(Money settlementAmount) {
		if (settlementAmount == null) {
			this.settlementAmount = new Money(0, 0);
		} else {
			this.settlementAmount = settlementAmount;
		}
	}

	public String getCanRedeem() {
		return canRedeem;
	}
	
	public void setCanRedeem(String canRedeem) {
		this.canRedeem = canRedeem;
	}

	public String getIsRoll() {
		return isRoll;
	}
	
	public void setIsRoll(String isRoll) {
		this.isRoll = isRoll;
	}

	public String getIsOpen() {
		return isOpen;
	}
	
	public void setIsOpen(String isOpen) {
		this.isOpen = isOpen;
	}

	public int getYearDayNum() {
		return yearDayNum;
	}
	
	public void setYearDayNum(int yearDayNum) {
		this.yearDayNum = yearDayNum;
	}

	public double getTransferedNum() {
		return transferedNum;
	}
	
	public void setTransferedNum(double transferedNum) {
		this.transferedNum = transferedNum;
	}

	public double getBuyBackNum() {
		return buyBackNum;
	}
	
	public void setBuyBackNum(double buyBackNum) {
		this.buyBackNum = buyBackNum;
	}

	public double getRedeemedNum() {
		return redeemedNum;
	}
	
	public void setRedeemedNum(double redeemedNum) {
		this.redeemedNum = redeemedNum;
	}

	public Date getPreFinishTime() {
		return preFinishTime;
	}
	
	public void setPreFinishTime(Date preFinishTime) {
		this.preFinishTime = preFinishTime;
	}

	public String getStatus() {
		return status;
	}
	
	public void setStatus(String status) {
		this.status = status;
	}

	public Date getRawAddTime() {
		return rawAddTime;
	}
	
	public void setRawAddTime(Date rawAddTime) {
		this.rawAddTime = rawAddTime;
	}

	public Date getRawUpdateTime() {
		return rawUpdateTime;
	}
	
	public void setRawUpdateTime(Date rawUpdateTime) {
		this.rawUpdateTime = rawUpdateTime;
	}


	/**
     * @return
     *
     * @see java.lang.Object#toString()
     */
	@Override
    public String toString() {

        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
