/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.rm.dal.daointerface;

// auto generated imports
import com.born.fcs.rm.dal.dataobject.SubmissionDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>submission</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/submission.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
 @SuppressWarnings("rawtypes") 
public interface SubmissionDAO {
	/**
	 *  Insert one <tt>SubmissionDO</tt> object to DB table <tt>submission</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into submission(report_name,report_code,report_year,report_month,reporter_id,reporter_account,reporter_name,dept_id,dept_code,dept_name,dept_path,dept_path_name,reporter_status,report_time,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param submission
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(SubmissionDO submission) throws DataAccessException;

	/**
	 *  Update DB table <tt>submission</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update submission set report_name=?, report_code=?, report_year=?, report_month=?, reporter_id=?, reporter_account=?, reporter_name=?, dept_id=?, dept_code=?, dept_name=?, dept_path=?, dept_path_name=?, reporter_status=?, report_time=? where (submission_id = ?)</tt>
	 *
	 *	@param submission
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(SubmissionDO submission) throws DataAccessException;

	/**
	 *  Query DB table <tt>submission</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from submission where (submission_id = ?)</tt>
	 *
	 *	@param submissionId
	 *	@return SubmissionDO
	 *	@throws DataAccessException
	 */	 
    public SubmissionDO findById(long submissionId) throws DataAccessException;

	/**
	 *  Query DB table <tt>submission</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select distinct s.dept_name from submission s where ((s.reporter_status != 'DELETED') AND (s.dept_name IS NOT NULL) AND (s.dept_name != '')) order by s.dept_name ASC</tt>
	 *
	 *	@return List<String>
	 *	@throws DataAccessException
	 */	 
    public List<String> findDepts() throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>submission</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from submission where (submission_id = ?)</tt>
	 *
	 *	@param submissionId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long submissionId) throws DataAccessException;

	/**
	 *  Query DB table <tt>submission</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from submission where ((1 = 1) AND (reporter_status != "DELETED"))</tt>
	 *
	 *	@param submission
	 *	@param startTime
	 *	@param endTime
	 *	@param statusList
	 *	@param deptList
	 *	@param draftUserId
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(SubmissionDO submission, String startTime, String endTime, List statusList, List deptList, Long draftUserId) throws DataAccessException;

	/**
	 *  Query DB table <tt>submission</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from submission where ((1 = 1) AND (reporter_status != "DELETED"))</tt>
	 *
	 *	@param submission
	 *	@param startTime
	 *	@param endTime
	 *	@param limitStart
	 *	@param pageSize
	 *	@param sortCol
	 *	@param sortOrder
	 *	@param statusList
	 *	@param deptList
	 *	@param draftUserId
	 *	@return List<SubmissionDO>
	 *	@throws DataAccessException
	 */	 
    public List<SubmissionDO> findByCondition(SubmissionDO submission, String startTime, String endTime, long limitStart, long pageSize, String sortCol, String sortOrder, List statusList, List deptList, Long draftUserId) throws DataAccessException;

}