/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.rm.dal.daointerface;

// auto generated imports
import com.born.fcs.rm.dal.dataobject.TestDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>test</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/test.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
 @SuppressWarnings("rawtypes") 
public interface TestDAO {
	/**
	 *  Insert one <tt>TestDO</tt> object to DB table <tt>test</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into test(test_key,test_value) values (?, ?)</tt>
	 *
	 *	@param test
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(TestDO test) throws DataAccessException;

	/**
	 *  Update DB table <tt>test</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update test set test_key=?, test_value=? where (test_id = ?)</tt>
	 *
	 *	@param test
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(TestDO test) throws DataAccessException;

	/**
	 *  Query DB table <tt>test</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from test where (test_id = ?)</tt>
	 *
	 *	@param testId
	 *	@return TestDO
	 *	@throws DataAccessException
	 */	 
    public TestDO findById(long testId) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>test</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from test where (test_id = ?)</tt>
	 *
	 *	@param testId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long testId) throws DataAccessException;

	/**
	 *  Query DB table <tt>test</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from test where (1 = 1)</tt>
	 *
	 *	@param test
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(TestDO test) throws DataAccessException;

	/**
	 *  Query DB table <tt>test</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from test where (1 = 1)</tt>
	 *
	 *	@param test
	 *	@param limitStart
	 *	@param pageSize
	 *	@param sortCol
	 *	@param sortOrder
	 *	@return List<TestDO>
	 *	@throws DataAccessException
	 */	 
    public List<TestDO> findByCondition(TestDO test, long limitStart, long pageSize, String sortCol, String sortOrder) throws DataAccessException;

}