/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.fcs.pm.dal.daointerface.CouncilJudgeDAO;


// auto generated imports
import com.born.fcs.pm.dal.dataobject.CouncilJudgeDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * An ibatis based implementation of dao interface <tt>com.born.fcs.pm.dal.daointerface.CouncilJudgeDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/council_judges.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 
@SuppressWarnings("unchecked")

public class IbatisCouncilJudgeDAO extends SqlMapClientDaoSupport implements CouncilJudgeDAO {
	/**
	 *  Insert one <tt>CouncilJudgeDO</tt> object to DB table <tt>council_judges</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into council_judges(council_id,council_code,judge_id,judge_name,compere,sort_order,raw_add_time) values (?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param councilJudge
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(CouncilJudgeDO councilJudge) throws DataAccessException {
    	if (councilJudge == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-COUNCIL-JUDGE-INSERT", councilJudge);

        return councilJudge.getId();
    }

	/**
	 *  Update DB table <tt>council_judges</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update council_judges set council_id=?, council_code=?, judge_id=?, judge_name=?, compere=?, sort_order=? where (id = ?)</tt>
	 *
	 *	@param councilJudge
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(CouncilJudgeDO councilJudge) throws DataAccessException {
    	if (councilJudge == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-COUNCIL-JUDGE-UPDATE", councilJudge);
    }

	/**
	 *  Query DB table <tt>council_judges</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from council_judges where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return CouncilJudgeDO
	 *	@throws DataAccessException
	 */	 
    public CouncilJudgeDO findById(long id) throws DataAccessException {
        Long param = new Long(id);

        return (CouncilJudgeDO) getSqlMapClientTemplate().queryForObject("MS-COUNCIL-JUDGE-FIND-BY-ID", param);

    }

	/**
	 *  Query DB table <tt>council_judges</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from council_judges where (council_id = ?) order by sort_order ASC</tt>
	 *
	 *	@param councilId
	 *	@return List<CouncilJudgeDO>
	 *	@throws DataAccessException
	 */	 
    public List<CouncilJudgeDO> findByCouncilId(long councilId) throws DataAccessException {
        Long param = new Long(councilId);

        return getSqlMapClientTemplate().queryForList("MS-COUNCIL-JUDGE-FIND-BY-COUNCIL-ID", param);

    }

	/**
	 *  Query DB table <tt>council_judges</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from council_judges where (council_code = ?) order by sort_order ASC</tt>
	 *
	 *	@param councilCode
	 *	@return List<CouncilJudgeDO>
	 *	@throws DataAccessException
	 */	 
    public List<CouncilJudgeDO> findByCouncilCode(String councilCode) throws DataAccessException {

        return getSqlMapClientTemplate().queryForList("MS-COUNCIL-JUDGE-FIND-BY-COUNCIL-CODE", councilCode);

    }

	/**
	 *  Delete records from DB table <tt>council_judges</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from council_judges where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException {
        Long param = new Long(id);

        return getSqlMapClientTemplate().delete("MS-COUNCIL-JUDGE-DELETE-BY-ID", param);
    }

	/**
	 *  Delete records from DB table <tt>council_judges</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from council_judges where (council_id = ?)</tt>
	 *
	 *	@param councilId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByCouncilId(long councilId) throws DataAccessException {
        Long param = new Long(councilId);

        return getSqlMapClientTemplate().delete("MS-COUNCIL-JUDGE-DELETE-BY-COUNCIL-ID", param);
    }

	/**
	 *  Delete records from DB table <tt>council_judges</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from council_judges where (council_code = ?)</tt>
	 *
	 *	@param councilCode
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByCouncilCode(String councilCode) throws DataAccessException {

        return getSqlMapClientTemplate().delete("MS-COUNCIL-JUDGE-DELETE-BY-COUNCIL-CODE", councilCode);
    }

}