/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.fcs.pm.dal.daointerface.FInvestigationCreditSchemeDAO;


// auto generated imports
import com.born.fcs.pm.dal.dataobject.FInvestigationCreditSchemeDO;
import org.springframework.dao.DataAccessException;

/**
 * An ibatis based implementation of dao interface <tt>com.born.fcs.pm.dal.daointerface.FInvestigationCreditSchemeDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/f_investigation_credit_scheme.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 

public class IbatisFInvestigationCreditSchemeDAO extends SqlMapClientDaoSupport implements FInvestigationCreditSchemeDAO {
	/**
	 *  Insert one <tt>FInvestigationCreditSchemeDO</tt> object to DB table <tt>f_investigation_credit_scheme</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into f_investigation_credit_scheme(form_id,project_code,project_name,customer_id,customer_name,industry_code,industry_name,credit_amount,time_limit,time_unit,busi_type,project_channel_id,project_channel_name,project_sub_channel_id,project_sub_channel_name,capital_channel_id,capital_channel_name,capital_sub_channel_id,capital_sub_channel_name,loan_purpose,repay_way,charge_phase,charge_way,charge_rate,charge_type,deposit,deposit_type,deposit_account,statement,other,process_flag,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param FInvestigationCreditScheme
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(FInvestigationCreditSchemeDO FInvestigationCreditScheme) throws DataAccessException {
    	if (FInvestigationCreditScheme == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-F-INVESTIGATION-CREDIT-SCHEME-INSERT", FInvestigationCreditScheme);

        return FInvestigationCreditScheme.getSchemeId();
    }

	/**
	 *  Update DB table <tt>f_investigation_credit_scheme</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update f_investigation_credit_scheme set form_id=?, project_code=?, project_name=?, customer_id=?, customer_name=?, industry_code=?, industry_name=?, credit_amount=?, time_limit=?, time_unit=?, busi_type=?, project_channel_id=?, project_channel_name=?, project_sub_channel_id=?, project_sub_channel_name=?, capital_channel_id=?, capital_channel_name=?, capital_sub_channel_id=?, capital_sub_channel_name=?, loan_purpose=?, repay_way=?, charge_phase=?, charge_way=?, charge_rate=?, charge_type=?, deposit=?, deposit_type=?, deposit_account=?, statement=?, other=?, process_flag=? where (scheme_id = ?)</tt>
	 *
	 *	@param FInvestigationCreditScheme
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(FInvestigationCreditSchemeDO FInvestigationCreditScheme) throws DataAccessException {
    	if (FInvestigationCreditScheme == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-F-INVESTIGATION-CREDIT-SCHEME-UPDATE", FInvestigationCreditScheme);
    }

	/**
	 *  Update DB table <tt>f_investigation_credit_scheme</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update f_investigation_credit_scheme set project_code=?, project_name=?, customer_id=?, customer_name=?, industry_code=?, industry_name=?, credit_amount=?, time_limit=?, time_unit=?, busi_type=?, project_channel_id=?, project_channel_name=?, project_sub_channel_id=?, project_sub_channel_name=?, capital_channel_id=?, capital_channel_name=?, capital_sub_channel_id=?, capital_sub_channel_name=?, loan_purpose=?, repay_way=?, charge_phase=?, charge_way=?, charge_rate=?, charge_type=?, deposit=?, deposit_type=?, deposit_account=?, statement=?, other=?, process_flag=? where (form_id = ?)</tt>
	 *
	 *	@param FInvestigationCreditScheme
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateByFormId(FInvestigationCreditSchemeDO FInvestigationCreditScheme) throws DataAccessException {
    	if (FInvestigationCreditScheme == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-F-INVESTIGATION-CREDIT-SCHEME-UPDATE-BY-FORM-ID", FInvestigationCreditScheme);
    }

	/**
	 *  Update DB table <tt>f_investigation_credit_scheme</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update f_investigation_credit_scheme set form_id=?, project_name=?, customer_id=?, customer_name=?, industry_code=?, industry_name=?, credit_amount=?, time_limit=?, time_unit=?, busi_type=?, project_channel_id=?, project_channel_name=?, project_sub_channel_id=?, project_sub_channel_name=?, capital_channel_id=?, capital_channel_name=?, capital_sub_channel_id=?, capital_sub_channel_name=?, loan_purpose=?, repay_way=?, charge_phase=?, charge_way=?, charge_rate=?, charge_type=?, deposit=?, deposit_type=?, deposit_account=?, statement=?, other=?, process_flag=? where (project_code = ?)</tt>
	 *
	 *	@param FInvestigationCreditScheme
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateByProjectCode(FInvestigationCreditSchemeDO FInvestigationCreditScheme) throws DataAccessException {
    	if (FInvestigationCreditScheme == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-F-INVESTIGATION-CREDIT-SCHEME-UPDATE-BY-PROJECT-CODE", FInvestigationCreditScheme);
    }

	/**
	 *  Query DB table <tt>f_investigation_credit_scheme</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_investigation_credit_scheme where (scheme_id = ?)</tt>
	 *
	 *	@param schemeId
	 *	@return FInvestigationCreditSchemeDO
	 *	@throws DataAccessException
	 */	 
    public FInvestigationCreditSchemeDO findById(long schemeId) throws DataAccessException {
        Long param = new Long(schemeId);

        return (FInvestigationCreditSchemeDO) getSqlMapClientTemplate().queryForObject("MS-F-INVESTIGATION-CREDIT-SCHEME-FIND-BY-ID", param);

    }

	/**
	 *  Query DB table <tt>f_investigation_credit_scheme</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_investigation_credit_scheme where (form_id = ?)</tt>
	 *
	 *	@param formId
	 *	@return FInvestigationCreditSchemeDO
	 *	@throws DataAccessException
	 */	 
    public FInvestigationCreditSchemeDO findByFormId(long formId) throws DataAccessException {
        Long param = new Long(formId);

        return (FInvestigationCreditSchemeDO) getSqlMapClientTemplate().queryForObject("MS-F-INVESTIGATION-CREDIT-SCHEME-FIND-BY-FORM-ID", param);

    }

	/**
	 *  Query DB table <tt>f_investigation_credit_scheme</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_investigation_credit_scheme where (project_code = ?)</tt>
	 *
	 *	@param projectCode
	 *	@return FInvestigationCreditSchemeDO
	 *	@throws DataAccessException
	 */	 
    public FInvestigationCreditSchemeDO findByProjectCode(String projectCode) throws DataAccessException {

        return (FInvestigationCreditSchemeDO) getSqlMapClientTemplate().queryForObject("MS-F-INVESTIGATION-CREDIT-SCHEME-FIND-BY-PROJECT-CODE", projectCode);

    }

	/**
	 *  Delete records from DB table <tt>f_investigation_credit_scheme</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_investigation_credit_scheme where (scheme_id = ?)</tt>
	 *
	 *	@param schemeId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long schemeId) throws DataAccessException {
        Long param = new Long(schemeId);

        return getSqlMapClientTemplate().delete("MS-F-INVESTIGATION-CREDIT-SCHEME-DELETE-BY-ID", param);
    }

	/**
	 *  Delete records from DB table <tt>f_investigation_credit_scheme</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_investigation_credit_scheme where (form_id = ?)</tt>
	 *
	 *	@param formId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByFormId(long formId) throws DataAccessException {
        Long param = new Long(formId);

        return getSqlMapClientTemplate().delete("MS-F-INVESTIGATION-CREDIT-SCHEME-DELETE-BY-FORM-ID", param);
    }

	/**
	 *  Delete records from DB table <tt>f_investigation_credit_scheme</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_investigation_credit_scheme where (project_code = ?)</tt>
	 *
	 *	@param projectCode
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByProjectCode(String projectCode) throws DataAccessException {

        return getSqlMapClientTemplate().delete("MS-F-INVESTIGATION-CREDIT-SCHEME-DELETE-BY-PROJECT-CODE", projectCode);
    }

}