## 报表规则设置
CREATE TABLE `report_rule` (
  `report_id` BIGINT(10) NOT NULL AUTO_INCREMENT COMMENT '报表id',
  `report_name` VARCHAR(200) NOT NULL COMMENT '报表名称',
  `sql_str` VARCHAR(10000) NOT NULL COMMENT '报表SQL主体',
  `access_roles` VARCHAR(50) DEFAULT NULL COMMENT '可访问改报表的角色列表',
  `note` VARCHAR(1000) DEFAULT NULL COMMENT '报表内容备注',
  `filter1_name` VARCHAR(100) DEFAULT NULL COMMENT '查询条件1名称',
  `filter1_type` VARCHAR(50) DEFAULT NULL COMMENT '查询条件1页面录入值的数据类型',
  `filter1_sql` VARCHAR(500) DEFAULT NULL COMMENT '查询条件1对应的SQL',
  `filter1_options` VARCHAR(1000) DEFAULT NULL COMMENT '查询条件1下拉框选项值',
  `filter2_name` VARCHAR(100) DEFAULT NULL COMMENT '查询条件2名称',
  `filter2_type` VARCHAR(50) DEFAULT NULL COMMENT '查询条件2页面录入值的数据类型',
  `filter2_sql` VARCHAR(500) DEFAULT NULL COMMENT '查询条件2对应的SQL',
  `filter2_options` VARCHAR(1000) DEFAULT NULL COMMENT '查询条件2下拉框选项值',
  `filter3_name` VARCHAR(100) DEFAULT NULL COMMENT '查询条件3名称',
  `filter3_type` VARCHAR(50) DEFAULT NULL COMMENT '查询条件3页面录入值的数据类型',
  `filter3_sql` VARCHAR(500) DEFAULT NULL COMMENT '查询条件3对应的SQL',
  `filter3_options` VARCHAR(1000) DEFAULT NULL COMMENT '查询条件3下拉框选项值',
  `filter4_name` VARCHAR(100) DEFAULT NULL COMMENT '查询条件4名称',
  `filter4_type` VARCHAR(50) DEFAULT NULL COMMENT '查询条件4页面录入值的数据类型',
  `filter4_sql` VARCHAR(500) DEFAULT NULL COMMENT '查询条件4对应的SQL',
  `filter4_options` VARCHAR(1000) DEFAULT NULL COMMENT '查询条件4下拉框选项值',
  `filter5_name` VARCHAR(100) DEFAULT NULL COMMENT '查询条件5名称',
  `filter5_type` VARCHAR(50) DEFAULT NULL COMMENT '查询条件5页面录入值的数据类型',
  `filter5_sql` VARCHAR(500) DEFAULT NULL COMMENT '查询条件5对应的SQL',
  `filter5_options` VARCHAR(1000) DEFAULT NULL COMMENT '查询条件5下拉框选项值',
  `filter6_name` VARCHAR(100) DEFAULT NULL COMMENT '查询条件6名称',
  `filter6_type` VARCHAR(50) DEFAULT NULL COMMENT '查询条件6页面录入值的数据类型',
  `filter6_sql` VARCHAR(500) DEFAULT NULL COMMENT '查询条件6对应的SQL',
  `filter6_options` VARCHAR(1000) DEFAULT NULL COMMENT '查询条件6下拉框选项值',
  `sort_order` INT(11) NOT NULL DEFAULT '0' COMMENT '排列顺序',
  PRIMARY KEY (`report_id`)
) ENGINE=INNODB AUTO_INCREMENT=43 DEFAULT CHARSET=utf8
