/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.rm.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.born.fcs.rm.dal.daointerface.RegularProjectRunInfoMonthDAO;


// auto generated imports
import com.born.fcs.rm.dal.dataobject.RegularProjectRunInfoMonthDO;
import org.springframework.dao.DataAccessException;
import java.util.Map;
	import java.util.HashMap;
	
/**
 * An ibatis based implementation of dao interface <tt>com.born.fcs.rm.dal.daointerface.RegularProjectRunInfoMonthDAO</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/regular_project_run_info_month.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */ 
@SuppressWarnings("rawtypes") 
public class IbatisRegularProjectRunInfoMonthDAO extends SqlMapClientDaoSupport implements RegularProjectRunInfoMonthDAO {
	/**
	 *  Insert one <tt>RegularProjectRunInfoMonthDO</tt> object to DB table <tt>regular_project_run_info_month</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into regular_project_run_info_month(report_date,report_year,report_month,customer_id,customer_name,busi_license_no,project_code,project_name,balance_beginning,balance_ending,occur_amount_this_year,occur_amount_this_month,occur_amount_this_month_detail,release_amount_this_year,release_amount_this_month,release_amount_this_month_detail,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param regularProjectRunInfoMonth
	 *	@return String
	 *	@throws DataAccessException
	 */	 
    public String insert(RegularProjectRunInfoMonthDO regularProjectRunInfoMonth) throws DataAccessException {
    	if (regularProjectRunInfoMonth == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-REGULAR-PROJECT-RUN-INFO-MONTH-INSERT", regularProjectRunInfoMonth);

        return regularProjectRunInfoMonth.getReportDate();
    }

	/**
	 *  Update DB table <tt>regular_project_run_info_month</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update regular_project_run_info_month set report_year=?, report_month=?, customer_id=?, customer_name=?, busi_license_no=?, project_name=?, balance_beginning=?, balance_ending=?, occur_amount_this_year=?, occur_amount_this_month=?, occur_amount_this_month_detail=?, release_amount_this_year=?, release_amount_this_month=?, release_amount_this_month_detail=? where ((report_date = ?) AND (project_code = ?))</tt>
	 *
	 *	@param regularProjectRunInfoMonth
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(RegularProjectRunInfoMonthDO regularProjectRunInfoMonth) throws DataAccessException {
    	if (regularProjectRunInfoMonth == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-REGULAR-PROJECT-RUN-INFO-MONTH-UPDATE", regularProjectRunInfoMonth);
    }

	/**
	 *  Query DB table <tt>regular_project_run_info_month</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from regular_project_run_info_month where ((report_date = ?) AND (project_code = ?))</tt>
	 *
	 *	@param reportDate
	 *	@param projectCode
	 *	@return RegularProjectRunInfoMonthDO
	 *	@throws DataAccessException
	 */	 
    public RegularProjectRunInfoMonthDO findByPrimary(String reportDate, String projectCode) throws DataAccessException {
        Map param = new HashMap();

        param.put("reportDate", reportDate);
        param.put("projectCode", projectCode);

        return (RegularProjectRunInfoMonthDO) getSqlMapClientTemplate().queryForObject("MS-REGULAR-PROJECT-RUN-INFO-MONTH-FIND-BY-PRIMARY", param);

    }

	/**
	 *  Delete records from DB table <tt>regular_project_run_info_month</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from regular_project_run_info_month where (report_date = ?)</tt>
	 *
	 *	@param reportDate
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByReportDate(String reportDate) throws DataAccessException {

        return getSqlMapClientTemplate().delete("MS-REGULAR-PROJECT-RUN-INFO-MONTH-DELETE-BY-REPORT-DATE", reportDate);
    }

}