/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.daointerface;

// auto generated imports
import com.born.fcs.pm.dal.dataobject.FCouncilSummaryProjectProcessControlDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>f_council_summary_project_process_control</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/f_council_summary_project_process_control.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
 @SuppressWarnings("rawtypes") 
public interface FCouncilSummaryProjectProcessControlDAO {
	/**
	 *  Insert one <tt>FCouncilSummaryProjectProcessControlDO</tt> object to DB table <tt>f_council_summary_project_process_control</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into f_council_summary_project_process_control(id,sp_id,type,up_rate,up_bp,down_rate,down_bp,content,sort_order,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param FCouncilSummaryProjectProcessControl
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(FCouncilSummaryProjectProcessControlDO FCouncilSummaryProjectProcessControl) throws DataAccessException;

	/**
	 *  Update DB table <tt>f_council_summary_project_process_control</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update f_council_summary_project_process_control set sp_id=?, type=?, up_rate=?, up_bp=?, down_rate=?, down_bp=?, content=?, sort_order=? where (id = ?)</tt>
	 *
	 *	@param FCouncilSummaryProjectProcessControl
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(FCouncilSummaryProjectProcessControlDO FCouncilSummaryProjectProcessControl) throws DataAccessException;

	/**
	 *  Query DB table <tt>f_council_summary_project_process_control</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_council_summary_project_process_control where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return FCouncilSummaryProjectProcessControlDO
	 *	@throws DataAccessException
	 */	 
    public FCouncilSummaryProjectProcessControlDO findById(long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>f_council_summary_project_process_control</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_council_summary_project_process_control where (sp_id = ?)</tt>
	 *
	 *	@param spId
	 *	@return List<FCouncilSummaryProjectProcessControlDO>
	 *	@throws DataAccessException
	 */	 
    public List<FCouncilSummaryProjectProcessControlDO> findBySpId(long spId) throws DataAccessException;

	/**
	 *  Query DB table <tt>f_council_summary_project_process_control</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_council_summary_project_process_control where ((sp_id = ?) AND (type = ?))</tt>
	 *
	 *	@param spId
	 *	@param type
	 *	@return List<FCouncilSummaryProjectProcessControlDO>
	 *	@throws DataAccessException
	 */	 
    public List<FCouncilSummaryProjectProcessControlDO> findBySpIdAndType(long spId, String type) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>f_council_summary_project_process_control</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_council_summary_project_process_control where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>f_council_summary_project_process_control</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_council_summary_project_process_control where (sp_id = ?)</tt>
	 *
	 *	@param spId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteBySpId(long spId) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>f_council_summary_project_process_control</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_council_summary_project_process_control where ((sp_id = ?) AND (type = ?))</tt>
	 *
	 *	@param spId
	 *	@param type
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteBySpIdAndType(long spId, String type) throws DataAccessException;

}