/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.daointerface;

// auto generated imports
import com.born.fcs.pm.dal.dataobject.FProjectCounterGuaranteePledgeDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>f_project_counter_guarantee_pledge</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/f_project_counter_guarantee_pledge.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
 @SuppressWarnings("rawtypes") 
public interface FProjectCounterGuaranteePledgeDAO {
	/**
	 *  Insert one <tt>FProjectCounterGuaranteePledgeDO</tt> object to DB table <tt>f_project_counter_guarantee_pledge</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into f_project_counter_guarantee_pledge(form_id,project_code,project_name,customer_id,customer_name,type,pledger,pledge_type,pledge_name,net_value,syn_position,postposition,sort_order,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param FProjectCounterGuaranteePledge
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(FProjectCounterGuaranteePledgeDO FProjectCounterGuaranteePledge) throws DataAccessException;

	/**
	 *  Update DB table <tt>f_project_counter_guarantee_pledge</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update f_project_counter_guarantee_pledge set form_id=?, project_code=?, project_name=?, customer_id=?, customer_name=?, type=?, pledger=?, pledge_type=?, pledge_name=?, net_value=?, syn_position=?, postposition=?, sort_order=? where (id = ?)</tt>
	 *
	 *	@param FProjectCounterGuaranteePledge
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(FProjectCounterGuaranteePledgeDO FProjectCounterGuaranteePledge) throws DataAccessException;

	/**
	 *  Update DB table <tt>f_project_counter_guarantee_pledge</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update f_project_counter_guarantee_pledge set project_code=?, project_name=?, customer_id=?, customer_name=? where (form_id = ?)</tt>
	 *
	 *	@param FProjectCounterGuaranteePledge
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateProjectAndCustomerInfoByFormId(FProjectCounterGuaranteePledgeDO FProjectCounterGuaranteePledge) throws DataAccessException;

	/**
	 *  Query DB table <tt>f_project_counter_guarantee_pledge</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_project_counter_guarantee_pledge where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return FProjectCounterGuaranteePledgeDO
	 *	@throws DataAccessException
	 */	 
    public FProjectCounterGuaranteePledgeDO findById(long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>f_project_counter_guarantee_pledge</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_project_counter_guarantee_pledge where (form_id = ?) order by sort_order ASC</tt>
	 *
	 *	@param formId
	 *	@return List<FProjectCounterGuaranteePledgeDO>
	 *	@throws DataAccessException
	 */	 
    public List<FProjectCounterGuaranteePledgeDO> findByFormId(long formId) throws DataAccessException;

	/**
	 *  Query DB table <tt>f_project_counter_guarantee_pledge</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_project_counter_guarantee_pledge where ((form_id = ?) AND (type = ?))</tt>
	 *
	 *	@param formId
	 *	@param type
	 *	@return List<FProjectCounterGuaranteePledgeDO>
	 *	@throws DataAccessException
	 */	 
    public List<FProjectCounterGuaranteePledgeDO> findByFormIdAndType(long formId, String type) throws DataAccessException;

	/**
	 *  Query DB table <tt>f_project_counter_guarantee_pledge</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_project_counter_guarantee_pledge where (project_code = ?) order by sort_order ASC</tt>
	 *
	 *	@param projectCode
	 *	@return List<FProjectCounterGuaranteePledgeDO>
	 *	@throws DataAccessException
	 */	 
    public List<FProjectCounterGuaranteePledgeDO> findByProjectCode(String projectCode) throws DataAccessException;

	/**
	 *  Query DB table <tt>f_project_counter_guarantee_pledge</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from f_project_counter_guarantee_pledge where ((project_code = ?) AND (type = ?))</tt>
	 *
	 *	@param projectCode
	 *	@param type
	 *	@return List<FProjectCounterGuaranteePledgeDO>
	 *	@throws DataAccessException
	 */	 
    public List<FProjectCounterGuaranteePledgeDO> findByProjectCodeAndType(String projectCode, String type) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>f_project_counter_guarantee_pledge</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_project_counter_guarantee_pledge where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long id) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>f_project_counter_guarantee_pledge</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_project_counter_guarantee_pledge where (form_id = ?)</tt>
	 *
	 *	@param formId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByFormId(long formId) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>f_project_counter_guarantee_pledge</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_project_counter_guarantee_pledge where ((form_id = ?) AND (type = ?))</tt>
	 *
	 *	@param formId
	 *	@param type
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByFormIdAndType(long formId, String type) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>f_project_counter_guarantee_pledge</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_project_counter_guarantee_pledge where (project_code = ?)</tt>
	 *
	 *	@param projectCode
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByProjectCode(String projectCode) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>f_project_counter_guarantee_pledge</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from f_project_counter_guarantee_pledge where ((project_code = ?) AND (type = ?))</tt>
	 *
	 *	@param projectCode
	 *	@param type
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByProjectCodeAndType(String projectCode, String type) throws DataAccessException;

}