/**
 * www.yiji.com Inc.
 * Copyright (c) 2011 All Rights Reserved.
 */
package com.born.fcs.pm.dal.daointerface;

// auto generated imports
import com.born.fcs.pm.dal.dataobject.MessageAlertDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>message_alert</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/message_alert.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
 @SuppressWarnings("rawtypes") 
public interface MessageAlertDAO {
	/**
	 *  Insert one <tt>MessageAlertDO</tt> object to DB table <tt>message_alert</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into message_alert(project_code,customer_name,alert_phrase,active,last_alert_time,raw_add_time) values (?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param messageAlert
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long insert(MessageAlertDO messageAlert) throws DataAccessException;

	/**
	 *  Update DB table <tt>message_alert</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update message_alert set project_code=?, customer_name=?, alert_phrase=?, active=?, last_alert_time=? where (alert_id = ?)</tt>
	 *
	 *	@param messageAlert
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(MessageAlertDO messageAlert) throws DataAccessException;

	/**
	 *  Update DB table <tt>message_alert</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update message_alert set customer_name=?, alert_phrase=?, active=?, last_alert_time=? where (project_code = ?)</tt>
	 *
	 *	@param messageAlert
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateByProjectCode(MessageAlertDO messageAlert) throws DataAccessException;

	/**
	 *  Update DB table <tt>message_alert</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update message_alert set active='NO' where ((project_code = ?) AND (alert_phrase = ?))</tt>
	 *
	 *	@param messageAlert
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateToStop(MessageAlertDO messageAlert) throws DataAccessException;

	/**
	 *  Query DB table <tt>message_alert</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from message_alert where (alert_id = ?)</tt>
	 *
	 *	@param alertId
	 *	@return MessageAlertDO
	 *	@throws DataAccessException
	 */	 
    public MessageAlertDO findById(long alertId) throws DataAccessException;

	/**
	 *  Query DB table <tt>message_alert</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from message_alert where (project_code = ?)</tt>
	 *
	 *	@param projectCode
	 *	@return List<MessageAlertDO>
	 *	@throws DataAccessException
	 */	 
    public List<MessageAlertDO> findByProjectCode(String projectCode) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>message_alert</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from message_alert where (alert_id = ?)</tt>
	 *
	 *	@param alertId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(long alertId) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>message_alert</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from message_alert where (project_code = ?)</tt>
	 *
	 *	@param projectCode
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByProjectCode(String projectCode) throws DataAccessException;

	/**
	 *  Query DB table <tt>message_alert</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from message_alert where (1 = 1)</tt>
	 *
	 *	@param messageAlert
	 *	@param limitStart
	 *	@param pageSize
	 *	@return List<MessageAlertDO>
	 *	@throws DataAccessException
	 */	 
    public List<MessageAlertDO> findByCondition(MessageAlertDO messageAlert, long limitStart, long pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>message_alert</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from message_alert where (1 = 1)</tt>
	 *
	 *	@param messageAlert
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findByConditionCount(MessageAlertDO messageAlert) throws DataAccessException;

}